// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: display_screens

#include "ui.h"

lv_obj_t * ui_airQualityScreen = NULL;
lv_obj_t * ui_airQualityScreenBackPanel = NULL;
lv_obj_t * ui_airQualityArc = NULL;
lv_obj_t * ui_airQualityStateText = NULL;
lv_obj_t * ui_airQualityLabelText = NULL;
lv_obj_t * ui_SeeStatButton = NULL;
lv_obj_t * ui_SeeStatButtonLabel = NULL;
lv_obj_t * ui_settingsButtonMain = NULL;
// event funtions
void ui_event_SeeStatButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_pmScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_pmScreen_screen_init);
        _ui_screen_delete(&ui_airQualityScreen);
    }
}

void ui_event_settingsButtonMain(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_wifiSelectionScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_wifiSelectionScreen_screen_init);
        _ui_screen_delete(&ui_airQualityScreen);
    }
}

// build funtions

void ui_airQualityScreen_screen_init(void)
{
    ui_airQualityScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_airQualityScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_airQualityScreenBackPanel = lv_obj_create(ui_airQualityScreen);
    lv_obj_set_width(ui_airQualityScreenBackPanel, 262);
    lv_obj_set_height(ui_airQualityScreenBackPanel, 173);
    lv_obj_set_x(ui_airQualityScreenBackPanel, 0);
    lv_obj_set_y(ui_airQualityScreenBackPanel, 4);
    lv_obj_set_align(ui_airQualityScreenBackPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_airQualityScreenBackPanel,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_radius(ui_airQualityScreenBackPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_airQualityScreenBackPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_airQualityScreenBackPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_airQualityScreenBackPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_airQualityArc = lv_arc_create(ui_airQualityScreenBackPanel);
    lv_obj_set_width(ui_airQualityArc, 150);
    lv_obj_set_height(ui_airQualityArc, 150);
    lv_obj_set_x(ui_airQualityArc, 0);
    lv_obj_set_y(ui_airQualityArc, 10);
    lv_obj_set_align(ui_airQualityArc, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_airQualityArc,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags
    lv_arc_set_value(ui_airQualityArc, 10);
    lv_arc_set_bg_angles(ui_airQualityArc, 180, 0);
    lv_obj_set_style_arc_color(ui_airQualityArc, lv_color_hex(0x707F78), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_airQualityArc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_airQualityArc, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_airQualityArc, lv_color_hex(0x0DB863), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_airQualityArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_airQualityArc, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_airQualityArc, lv_color_hex(0x84D4AC), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_airQualityArc, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_airQualityArc, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_airQualityArc, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_airQualityArc, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_airQualityArc, 2, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_airQualityStateText = lv_label_create(ui_airQualityScreenBackPanel);
    lv_obj_set_width(ui_airQualityStateText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_airQualityStateText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_airQualityStateText, 0);
    lv_obj_set_y(ui_airQualityStateText, -10);
    lv_obj_set_align(ui_airQualityStateText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_airQualityStateText, "GOOD");
    lv_obj_remove_flag(ui_airQualityStateText, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags
    lv_obj_set_style_text_color(ui_airQualityStateText, lv_color_hex(0x0DB863), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_airQualityStateText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_airQualityStateText, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_airQualityStateText, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_airQualityLabelText = lv_label_create(ui_airQualityScreenBackPanel);
    lv_obj_set_width(ui_airQualityLabelText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_airQualityLabelText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_airQualityLabelText, 0);
    lv_obj_set_y(ui_airQualityLabelText, 13);
    lv_obj_set_align(ui_airQualityLabelText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_airQualityLabelText, "Air Quality");
    lv_obj_remove_flag(ui_airQualityLabelText, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags
    lv_obj_set_style_text_color(ui_airQualityLabelText, lv_color_hex(0x0DB863), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_airQualityLabelText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_airQualityLabelText, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_airQualityLabelText, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SeeStatButton = lv_button_create(ui_airQualityScreen);
    lv_obj_set_width(ui_SeeStatButton, 52);
    lv_obj_set_height(ui_SeeStatButton, 33);
    lv_obj_set_x(ui_SeeStatButton, 0);
    lv_obj_set_y(ui_SeeStatButton, 83);
    lv_obj_set_align(ui_SeeStatButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SeeStatButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_SeeStatButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SeeStatButton, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SeeStatButton, lv_color_hex(0x7C9EE7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SeeStatButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SeeStatButtonLabel = lv_label_create(ui_SeeStatButton);
    lv_obj_set_width(ui_SeeStatButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SeeStatButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SeeStatButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SeeStatButtonLabel, "STATS");
    lv_obj_set_style_text_font(ui_SeeStatButtonLabel, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settingsButtonMain = lv_button_create(ui_airQualityScreen);
    lv_obj_set_width(ui_settingsButtonMain, 34);
    lv_obj_set_height(ui_settingsButtonMain, 30);
    lv_obj_set_x(ui_settingsButtonMain, 140);
    lv_obj_set_y(ui_settingsButtonMain, -101);
    lv_obj_set_align(ui_settingsButtonMain, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_settingsButtonMain, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_settingsButtonMain, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_settingsButtonMain, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_settingsButtonMain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_settingsButtonMain, &ui_img_settingsicon_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_SeeStatButton, ui_event_SeeStatButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_settingsButtonMain, ui_event_settingsButtonMain, LV_EVENT_ALL, NULL);

}

void ui_airQualityScreen_screen_destroy(void)
{
    if(ui_airQualityScreen) lv_obj_del(ui_airQualityScreen);

    // NULL screen variables
    ui_airQualityScreen = NULL;
    ui_airQualityScreenBackPanel = NULL;
    ui_airQualityArc = NULL;
    ui_airQualityStateText = NULL;
    ui_airQualityLabelText = NULL;
    ui_SeeStatButton = NULL;
    ui_SeeStatButtonLabel = NULL;
    ui_settingsButtonMain = NULL;

}
