// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: display_screens

#include "ui.h"

lv_obj_t * ui_co2Screen = NULL;
lv_obj_t * ui_topPanelCO2 = NULL;
lv_obj_t * ui_pMScreenButtonCO2 = NULL;
lv_obj_t * ui_pMScreenButtonLabelCO2 = NULL;
lv_obj_t * ui_tempScreenButtonCO2 = NULL;
lv_obj_t * ui_tempScreenButtonLabelCO2 = NULL;
lv_obj_t * ui_vocScreenButtonVocCO2 = NULL;
lv_obj_t * ui_vocScreenButtonLabelCO2 = NULL;
lv_obj_t * ui_co2ScreenButtonVocCO2 = NULL;
lv_obj_t * ui_co2ScreenButtonLabelCO2 = NULL;
lv_obj_t * ui_CO2ScreenBackPanel = NULL;
lv_obj_t * ui_CO2Panel = NULL;
lv_obj_t * ui_CO2Arc = NULL;
lv_obj_t * ui_CO2StateText = NULL;
lv_obj_t * ui_CO2ValueText = NULL;
lv_obj_t * ui_CO2LabelText = NULL;
lv_obj_t * ui_homeButtonCO2 = NULL;
lv_obj_t * ui_settingsButtonCO2 = NULL;
lv_obj_t * ui_leftArrowButtonCO2 = NULL;
// event funtions
void ui_event_pMScreenButtonCO2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_pmScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_pmScreen_screen_init);
        _ui_screen_delete(&ui_co2Screen);
    }
}

void ui_event_tempScreenButtonCO2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_tempScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_tempScreen_screen_init);
        _ui_screen_delete(&ui_co2Screen);
    }
}

void ui_event_vocScreenButtonVocCO2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_vocScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_vocScreen_screen_init);
        _ui_screen_delete(&ui_co2Screen);
    }
}

void ui_event_homeButtonCO2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_airQualityScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_airQualityScreen_screen_init);
        _ui_screen_delete(&ui_co2Screen);
    }
}

void ui_event_settingsButtonCO2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_wifiSelectionScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_wifiSelectionScreen_screen_init);
        _ui_screen_delete(&ui_co2Screen);
    }
}

void ui_event_leftArrowButtonCO2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_vocScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_vocScreen_screen_init);
        _ui_screen_delete(&ui_co2Screen);
    }
}

// build funtions

void ui_co2Screen_screen_init(void)
{
    ui_co2Screen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_co2Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_topPanelCO2 = lv_obj_create(ui_co2Screen);
    lv_obj_set_width(ui_topPanelCO2, 327);
    lv_obj_set_height(ui_topPanelCO2, 30);
    lv_obj_set_x(ui_topPanelCO2, 0);
    lv_obj_set_y(ui_topPanelCO2, -100);
    lv_obj_set_align(ui_topPanelCO2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_topPanelCO2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_topPanelCO2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_topPanelCO2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_topPanelCO2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_topPanelCO2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_topPanelCO2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_topPanelCO2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pMScreenButtonCO2 = lv_button_create(ui_topPanelCO2);
    lv_obj_set_width(ui_pMScreenButtonCO2, 58);
    lv_obj_set_height(ui_pMScreenButtonCO2, 30);
    lv_obj_set_x(ui_pMScreenButtonCO2, 0);
    lv_obj_set_y(ui_pMScreenButtonCO2, -37);
    lv_obj_set_align(ui_pMScreenButtonCO2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pMScreenButtonCO2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_pMScreenButtonCO2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pMScreenButtonCO2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pMScreenButtonCO2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pMScreenButtonCO2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pMScreenButtonLabelCO2 = lv_label_create(ui_pMScreenButtonCO2);
    lv_obj_set_width(ui_pMScreenButtonLabelCO2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pMScreenButtonLabelCO2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_pMScreenButtonLabelCO2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pMScreenButtonLabelCO2, "PM");
    lv_obj_set_style_text_font(ui_pMScreenButtonLabelCO2, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempScreenButtonCO2 = lv_button_create(ui_topPanelCO2);
    lv_obj_set_width(ui_tempScreenButtonCO2, 58);
    lv_obj_set_height(ui_tempScreenButtonCO2, 30);
    lv_obj_set_x(ui_tempScreenButtonCO2, 0);
    lv_obj_set_y(ui_tempScreenButtonCO2, -37);
    lv_obj_set_align(ui_tempScreenButtonCO2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_tempScreenButtonCO2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_tempScreenButtonCO2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_tempScreenButtonCO2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_tempScreenButtonCO2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_tempScreenButtonCO2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempScreenButtonLabelCO2 = lv_label_create(ui_tempScreenButtonCO2);
    lv_obj_set_width(ui_tempScreenButtonLabelCO2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tempScreenButtonLabelCO2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_tempScreenButtonLabelCO2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tempScreenButtonLabelCO2, "TEMP");
    lv_obj_set_style_text_font(ui_tempScreenButtonLabelCO2, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_vocScreenButtonVocCO2 = lv_button_create(ui_topPanelCO2);
    lv_obj_set_width(ui_vocScreenButtonVocCO2, 58);
    lv_obj_set_height(ui_vocScreenButtonVocCO2, 30);
    lv_obj_set_x(ui_vocScreenButtonVocCO2, 0);
    lv_obj_set_y(ui_vocScreenButtonVocCO2, -37);
    lv_obj_set_align(ui_vocScreenButtonVocCO2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_vocScreenButtonVocCO2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_vocScreenButtonVocCO2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_vocScreenButtonVocCO2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_vocScreenButtonVocCO2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_vocScreenButtonVocCO2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_vocScreenButtonLabelCO2 = lv_label_create(ui_vocScreenButtonVocCO2);
    lv_obj_set_width(ui_vocScreenButtonLabelCO2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_vocScreenButtonLabelCO2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_vocScreenButtonLabelCO2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_vocScreenButtonLabelCO2, "VOC");
    lv_obj_set_style_text_font(ui_vocScreenButtonLabelCO2, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_co2ScreenButtonVocCO2 = lv_button_create(ui_topPanelCO2);
    lv_obj_set_width(ui_co2ScreenButtonVocCO2, 58);
    lv_obj_set_height(ui_co2ScreenButtonVocCO2, 30);
    lv_obj_set_x(ui_co2ScreenButtonVocCO2, 0);
    lv_obj_set_y(ui_co2ScreenButtonVocCO2, -37);
    lv_obj_set_align(ui_co2ScreenButtonVocCO2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_co2ScreenButtonVocCO2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_co2ScreenButtonVocCO2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_co2ScreenButtonVocCO2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_co2ScreenButtonVocCO2, lv_color_hex(0x7C9EE7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_co2ScreenButtonVocCO2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_co2ScreenButtonLabelCO2 = lv_label_create(ui_co2ScreenButtonVocCO2);
    lv_obj_set_width(ui_co2ScreenButtonLabelCO2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_co2ScreenButtonLabelCO2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_co2ScreenButtonLabelCO2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_co2ScreenButtonLabelCO2, "CO2");
    lv_obj_set_style_text_font(ui_co2ScreenButtonLabelCO2, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CO2ScreenBackPanel = lv_obj_create(ui_co2Screen);
    lv_obj_set_width(ui_CO2ScreenBackPanel, 267);
    lv_obj_set_height(ui_CO2ScreenBackPanel, 194);
    lv_obj_set_x(ui_CO2ScreenBackPanel, 0);
    lv_obj_set_y(ui_CO2ScreenBackPanel, 19);
    lv_obj_set_align(ui_CO2ScreenBackPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_CO2ScreenBackPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_CO2ScreenBackPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CO2ScreenBackPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CO2ScreenBackPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_CO2ScreenBackPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CO2Panel = lv_obj_create(ui_CO2ScreenBackPanel);
    lv_obj_set_width(ui_CO2Panel, 82);
    lv_obj_set_height(ui_CO2Panel, 85);
    lv_obj_set_x(ui_CO2Panel, 0);
    lv_obj_set_y(ui_CO2Panel, -15);
    lv_obj_set_align(ui_CO2Panel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_CO2Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_CO2Panel, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_CO2Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CO2Arc = lv_arc_create(ui_CO2Panel);
    lv_obj_set_width(ui_CO2Arc, 63);
    lv_obj_set_height(ui_CO2Arc, 64);
    lv_obj_set_align(ui_CO2Arc, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_CO2Arc, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK |
                       LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags
    lv_arc_set_range(ui_CO2Arc, 400, 1300);
    lv_arc_set_value(ui_CO2Arc, 600);
    lv_obj_set_style_arc_color(ui_CO2Arc, lv_color_hex(0x707F78), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_CO2Arc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_CO2Arc, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_CO2Arc, lv_color_hex(0xDADA12), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_CO2Arc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_CO2Arc, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_CO2Arc, lv_color_hex(0xDDDDA5), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CO2Arc, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_CO2Arc, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_CO2Arc, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_CO2Arc, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_CO2Arc, 2, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_CO2StateText = lv_label_create(ui_CO2Panel);
    lv_obj_set_width(ui_CO2StateText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CO2StateText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_CO2StateText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CO2StateText, "FAIR");
    lv_obj_set_style_text_color(ui_CO2StateText, lv_color_hex(0xDADA12), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CO2StateText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_CO2StateText, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CO2StateText, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CO2ValueText = lv_label_create(ui_CO2Panel);
    lv_obj_set_width(ui_CO2ValueText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CO2ValueText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CO2ValueText, 1);
    lv_obj_set_y(ui_CO2ValueText, 19);
    lv_obj_set_align(ui_CO2ValueText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CO2ValueText, "600");
    lv_obj_set_style_text_color(ui_CO2ValueText, lv_color_hex(0xDADA12), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CO2ValueText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_CO2ValueText, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CO2ValueText, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CO2LabelText = lv_label_create(ui_CO2Panel);
    lv_obj_set_width(ui_CO2LabelText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CO2LabelText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CO2LabelText, 1);
    lv_obj_set_y(ui_CO2LabelText, 32);
    lv_obj_set_align(ui_CO2LabelText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CO2LabelText, "CO2");
    lv_obj_set_style_text_color(ui_CO2LabelText, lv_color_hex(0xDADA12), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CO2LabelText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_CO2LabelText, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CO2LabelText, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_homeButtonCO2 = lv_button_create(ui_CO2ScreenBackPanel);
    lv_obj_set_width(ui_homeButtonCO2, 30);
    lv_obj_set_height(ui_homeButtonCO2, 30);
    lv_obj_set_x(ui_homeButtonCO2, 0);
    lv_obj_set_y(ui_homeButtonCO2, 77);
    lv_obj_set_align(ui_homeButtonCO2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_homeButtonCO2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_homeButtonCO2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_homeButtonCO2, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_homeButtonCO2, lv_color_hex(0x7C9EE7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_homeButtonCO2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_homeButtonCO2, &ui_img_homeicon_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settingsButtonCO2 = lv_button_create(ui_co2Screen);
    lv_obj_set_width(ui_settingsButtonCO2, 34);
    lv_obj_set_height(ui_settingsButtonCO2, 30);
    lv_obj_set_x(ui_settingsButtonCO2, 140);
    lv_obj_set_y(ui_settingsButtonCO2, -101);
    lv_obj_set_align(ui_settingsButtonCO2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_settingsButtonCO2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_settingsButtonCO2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_settingsButtonCO2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_settingsButtonCO2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_settingsButtonCO2, &ui_img_settingsicon_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_leftArrowButtonCO2 = lv_button_create(ui_co2Screen);
    lv_obj_set_width(ui_leftArrowButtonCO2, 28);
    lv_obj_set_height(ui_leftArrowButtonCO2, 67);
    lv_obj_set_x(ui_leftArrowButtonCO2, -138);
    lv_obj_set_y(ui_leftArrowButtonCO2, 0);
    lv_obj_set_align(ui_leftArrowButtonCO2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_leftArrowButtonCO2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_leftArrowButtonCO2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_leftArrowButtonCO2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_leftArrowButtonCO2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_leftArrowButtonCO2, &ui_img_leftarrowicon_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_pMScreenButtonCO2, ui_event_pMScreenButtonCO2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_tempScreenButtonCO2, ui_event_tempScreenButtonCO2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_vocScreenButtonVocCO2, ui_event_vocScreenButtonVocCO2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_homeButtonCO2, ui_event_homeButtonCO2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_settingsButtonCO2, ui_event_settingsButtonCO2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_leftArrowButtonCO2, ui_event_leftArrowButtonCO2, LV_EVENT_ALL, NULL);

}

void ui_co2Screen_screen_destroy(void)
{
    if(ui_co2Screen) lv_obj_del(ui_co2Screen);

    // NULL screen variables
    ui_co2Screen = NULL;
    ui_topPanelCO2 = NULL;
    ui_pMScreenButtonCO2 = NULL;
    ui_pMScreenButtonLabelCO2 = NULL;
    ui_tempScreenButtonCO2 = NULL;
    ui_tempScreenButtonLabelCO2 = NULL;
    ui_vocScreenButtonVocCO2 = NULL;
    ui_vocScreenButtonLabelCO2 = NULL;
    ui_co2ScreenButtonVocCO2 = NULL;
    ui_co2ScreenButtonLabelCO2 = NULL;
    ui_CO2ScreenBackPanel = NULL;
    ui_CO2Panel = NULL;
    ui_CO2Arc = NULL;
    ui_CO2StateText = NULL;
    ui_CO2ValueText = NULL;
    ui_CO2LabelText = NULL;
    ui_homeButtonCO2 = NULL;
    ui_settingsButtonCO2 = NULL;
    ui_leftArrowButtonCO2 = NULL;

}
