// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: display_screens

#include "ui.h"

lv_obj_t * ui_pmScreen = NULL;
lv_obj_t * ui_topPanelPM = NULL;
lv_obj_t * ui_pMScreenButtonPM = NULL;
lv_obj_t * ui_pMScreenButtonLabel = NULL;
lv_obj_t * ui_tempScreenButtonPM = NULL;
lv_obj_t * ui_tempScreenButtonLabel = NULL;
lv_obj_t * ui_vocScreenButtonPM = NULL;
lv_obj_t * ui_vocScreenButtonLabel = NULL;
lv_obj_t * ui_co2ScreenButtonPM = NULL;
lv_obj_t * ui_co2ScreenButtonLabel = NULL;
lv_obj_t * ui_pmScreenBackPanel = NULL;
lv_obj_t * ui_pm10Panel = NULL;
lv_obj_t * ui_pm10Arc = NULL;
lv_obj_t * ui_pm10StateText = NULL;
lv_obj_t * ui_pm10ValueText = NULL;
lv_obj_t * ui_pm10LabelText = NULL;
lv_obj_t * ui_pm25Panel = NULL;
lv_obj_t * ui_pm25Arc = NULL;
lv_obj_t * ui_pm25StateText = NULL;
lv_obj_t * ui_pm25ValueText = NULL;
lv_obj_t * ui_pm25LabelText = NULL;
lv_obj_t * ui_pm40Panel = NULL;
lv_obj_t * ui_pm40Arc = NULL;
lv_obj_t * ui_pm40StateText = NULL;
lv_obj_t * ui_pm40ValueText = NULL;
lv_obj_t * ui_pm40LabelText = NULL;
lv_obj_t * ui_pm100Panel = NULL;
lv_obj_t * ui_pm100Arc = NULL;
lv_obj_t * ui_pm100StateText = NULL;
lv_obj_t * ui_pm100ValueText = NULL;
lv_obj_t * ui_pm100LabelText = NULL;
lv_obj_t * ui_homeButtonPM = NULL;
lv_obj_t * ui_rightArrowButtonPM = NULL;
lv_obj_t * ui_settingsButtonPM = NULL;
// event funtions
void ui_event_tempScreenButtonPM(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_tempScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_tempScreen_screen_init);
        _ui_screen_delete(&ui_pmScreen);
    }
}

void ui_event_vocScreenButtonPM(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_vocScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_vocScreen_screen_init);
        _ui_screen_delete(&ui_pmScreen);
    }
}

void ui_event_co2ScreenButtonPM(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_co2Screen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_co2Screen_screen_init);
        _ui_screen_delete(&ui_pmScreen);
    }
}

void ui_event_homeButtonPM(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_airQualityScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_airQualityScreen_screen_init);
        _ui_screen_delete(&ui_pmScreen);
    }
}

void ui_event_rightArrowButtonPM(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_tempScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_tempScreen_screen_init);
        _ui_screen_delete(&ui_pmScreen);
    }
}

void ui_event_settingsButtonPM(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_wifiSelectionScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_wifiSelectionScreen_screen_init);
        _ui_screen_delete(&ui_pmScreen);
    }
}

// build funtions

void ui_pmScreen_screen_init(void)
{
    ui_pmScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_pmScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_topPanelPM = lv_obj_create(ui_pmScreen);
    lv_obj_set_width(ui_topPanelPM, 327);
    lv_obj_set_height(ui_topPanelPM, 30);
    lv_obj_set_x(ui_topPanelPM, 0);
    lv_obj_set_y(ui_topPanelPM, -100);
    lv_obj_set_align(ui_topPanelPM, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_topPanelPM, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_topPanelPM, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_topPanelPM, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_topPanelPM, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_topPanelPM, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_topPanelPM, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_topPanelPM, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pMScreenButtonPM = lv_button_create(ui_topPanelPM);
    lv_obj_set_width(ui_pMScreenButtonPM, 58);
    lv_obj_set_height(ui_pMScreenButtonPM, 30);
    lv_obj_set_x(ui_pMScreenButtonPM, 0);
    lv_obj_set_y(ui_pMScreenButtonPM, -37);
    lv_obj_set_align(ui_pMScreenButtonPM, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pMScreenButtonPM, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_pMScreenButtonPM, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pMScreenButtonPM, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pMScreenButtonPM, lv_color_hex(0x7C9EE7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pMScreenButtonPM, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pMScreenButtonLabel = lv_label_create(ui_pMScreenButtonPM);
    lv_obj_set_width(ui_pMScreenButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pMScreenButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_pMScreenButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pMScreenButtonLabel, "PM");
    lv_obj_set_style_text_font(ui_pMScreenButtonLabel, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempScreenButtonPM = lv_button_create(ui_topPanelPM);
    lv_obj_set_width(ui_tempScreenButtonPM, 58);
    lv_obj_set_height(ui_tempScreenButtonPM, 30);
    lv_obj_set_x(ui_tempScreenButtonPM, 0);
    lv_obj_set_y(ui_tempScreenButtonPM, -37);
    lv_obj_set_align(ui_tempScreenButtonPM, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_tempScreenButtonPM, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_tempScreenButtonPM, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_tempScreenButtonPM, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_tempScreenButtonPM, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_tempScreenButtonPM, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempScreenButtonLabel = lv_label_create(ui_tempScreenButtonPM);
    lv_obj_set_width(ui_tempScreenButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tempScreenButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_tempScreenButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tempScreenButtonLabel, "TEMP");
    lv_obj_set_style_text_font(ui_tempScreenButtonLabel, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_vocScreenButtonPM = lv_button_create(ui_topPanelPM);
    lv_obj_set_width(ui_vocScreenButtonPM, 58);
    lv_obj_set_height(ui_vocScreenButtonPM, 30);
    lv_obj_set_x(ui_vocScreenButtonPM, 0);
    lv_obj_set_y(ui_vocScreenButtonPM, -37);
    lv_obj_set_align(ui_vocScreenButtonPM, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_vocScreenButtonPM, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_vocScreenButtonPM, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_vocScreenButtonPM, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_vocScreenButtonPM, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_vocScreenButtonPM, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_vocScreenButtonLabel = lv_label_create(ui_vocScreenButtonPM);
    lv_obj_set_width(ui_vocScreenButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_vocScreenButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_vocScreenButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_vocScreenButtonLabel, "VOC");
    lv_obj_set_style_text_font(ui_vocScreenButtonLabel, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_co2ScreenButtonPM = lv_button_create(ui_topPanelPM);
    lv_obj_set_width(ui_co2ScreenButtonPM, 58);
    lv_obj_set_height(ui_co2ScreenButtonPM, 30);
    lv_obj_set_x(ui_co2ScreenButtonPM, 0);
    lv_obj_set_y(ui_co2ScreenButtonPM, -37);
    lv_obj_set_align(ui_co2ScreenButtonPM, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_co2ScreenButtonPM, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_co2ScreenButtonPM, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_co2ScreenButtonPM, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_co2ScreenButtonPM, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_co2ScreenButtonPM, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_co2ScreenButtonLabel = lv_label_create(ui_co2ScreenButtonPM);
    lv_obj_set_width(ui_co2ScreenButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_co2ScreenButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_co2ScreenButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_co2ScreenButtonLabel, "CO2");
    lv_obj_set_style_text_font(ui_co2ScreenButtonLabel, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pmScreenBackPanel = lv_obj_create(ui_pmScreen);
    lv_obj_set_width(ui_pmScreenBackPanel, 267);
    lv_obj_set_height(ui_pmScreenBackPanel, 194);
    lv_obj_set_x(ui_pmScreenBackPanel, 0);
    lv_obj_set_y(ui_pmScreenBackPanel, 19);
    lv_obj_set_align(ui_pmScreenBackPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_pmScreenBackPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pmScreenBackPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pmScreenBackPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pmScreenBackPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pmScreenBackPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pm10Panel = lv_obj_create(ui_pmScreenBackPanel);
    lv_obj_set_width(ui_pm10Panel, 82);
    lv_obj_set_height(ui_pm10Panel, 85);
    lv_obj_set_x(ui_pm10Panel, -67);
    lv_obj_set_y(ui_pm10Panel, -47);
    lv_obj_set_align(ui_pm10Panel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_pm10Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pm10Panel, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pm10Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pm10Arc = lv_arc_create(ui_pm10Panel);
    lv_obj_set_width(ui_pm10Arc, 63);
    lv_obj_set_height(ui_pm10Arc, 64);
    lv_obj_set_align(ui_pm10Arc, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_pm10Arc, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK |
                       LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags
    lv_arc_set_range(ui_pm10Arc, 0, 150);
    lv_arc_set_value(ui_pm10Arc, 10);
    lv_obj_set_style_arc_color(ui_pm10Arc, lv_color_hex(0x707F78), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_pm10Arc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_pm10Arc, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_pm10Arc, lv_color_hex(0x0DB863), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_pm10Arc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_pm10Arc, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_pm10Arc, lv_color_hex(0x84D4AC), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pm10Arc, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_pm10Arc, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_pm10Arc, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_pm10Arc, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_pm10Arc, 2, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_pm10StateText = lv_label_create(ui_pm10Panel);
    lv_obj_set_width(ui_pm10StateText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pm10StateText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_pm10StateText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pm10StateText, "GOOD");
    lv_obj_set_style_text_color(ui_pm10StateText, lv_color_hex(0x0DB863), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pm10StateText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_pm10StateText, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pm10StateText, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pm10ValueText = lv_label_create(ui_pm10Panel);
    lv_obj_set_width(ui_pm10ValueText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pm10ValueText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pm10ValueText, 1);
    lv_obj_set_y(ui_pm10ValueText, 19);
    lv_obj_set_align(ui_pm10ValueText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pm10ValueText, "10");
    lv_obj_set_style_text_color(ui_pm10ValueText, lv_color_hex(0x0DB863), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pm10ValueText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_pm10ValueText, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pm10ValueText, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pm10LabelText = lv_label_create(ui_pm10Panel);
    lv_obj_set_width(ui_pm10LabelText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pm10LabelText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pm10LabelText, 1);
    lv_obj_set_y(ui_pm10LabelText, 32);
    lv_obj_set_align(ui_pm10LabelText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pm10LabelText, "PM 1.0");
    lv_obj_set_style_text_color(ui_pm10LabelText, lv_color_hex(0x0DB863), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pm10LabelText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_pm10LabelText, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pm10LabelText, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pm25Panel = lv_obj_create(ui_pmScreenBackPanel);
    lv_obj_set_width(ui_pm25Panel, 82);
    lv_obj_set_height(ui_pm25Panel, 85);
    lv_obj_set_x(ui_pm25Panel, 67);
    lv_obj_set_y(ui_pm25Panel, -47);
    lv_obj_set_align(ui_pm25Panel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_pm25Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pm25Panel, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pm25Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pm25Arc = lv_arc_create(ui_pm25Panel);
    lv_obj_set_width(ui_pm25Arc, 63);
    lv_obj_set_height(ui_pm25Arc, 64);
    lv_obj_set_align(ui_pm25Arc, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_pm25Arc, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK |
                       LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags
    lv_arc_set_range(ui_pm25Arc, 0, 250);
    lv_arc_set_value(ui_pm25Arc, 35);
    lv_obj_set_style_arc_color(ui_pm25Arc, lv_color_hex(0x707F78), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_pm25Arc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_pm25Arc, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_pm25Arc, lv_color_hex(0xDADA12), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_pm25Arc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_pm25Arc, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_pm25Arc, lv_color_hex(0xDDDDA5), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pm25Arc, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_pm25Arc, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_pm25Arc, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_pm25Arc, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_pm25Arc, 2, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_pm25StateText = lv_label_create(ui_pm25Panel);
    lv_obj_set_width(ui_pm25StateText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pm25StateText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_pm25StateText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pm25StateText, "FAIR");
    lv_obj_set_style_text_color(ui_pm25StateText, lv_color_hex(0xDADA12), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pm25StateText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_pm25StateText, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pm25StateText, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pm25ValueText = lv_label_create(ui_pm25Panel);
    lv_obj_set_width(ui_pm25ValueText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pm25ValueText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pm25ValueText, 1);
    lv_obj_set_y(ui_pm25ValueText, 19);
    lv_obj_set_align(ui_pm25ValueText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pm25ValueText, "32");
    lv_obj_set_style_text_color(ui_pm25ValueText, lv_color_hex(0xDADA12), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pm25ValueText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_pm25ValueText, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pm25ValueText, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pm25LabelText = lv_label_create(ui_pm25Panel);
    lv_obj_set_width(ui_pm25LabelText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pm25LabelText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pm25LabelText, 1);
    lv_obj_set_y(ui_pm25LabelText, 32);
    lv_obj_set_align(ui_pm25LabelText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pm25LabelText, "PM 2.5");
    lv_obj_set_style_text_color(ui_pm25LabelText, lv_color_hex(0xDADA12), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pm25LabelText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_pm25LabelText, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pm25LabelText, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pm40Panel = lv_obj_create(ui_pmScreenBackPanel);
    lv_obj_set_width(ui_pm40Panel, 82);
    lv_obj_set_height(ui_pm40Panel, 85);
    lv_obj_set_x(ui_pm40Panel, -67);
    lv_obj_set_y(ui_pm40Panel, 47);
    lv_obj_set_align(ui_pm40Panel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_pm40Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pm40Panel, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pm40Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pm40Arc = lv_arc_create(ui_pm40Panel);
    lv_obj_set_width(ui_pm40Arc, 63);
    lv_obj_set_height(ui_pm40Arc, 64);
    lv_obj_set_align(ui_pm40Arc, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_pm40Arc, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK |
                       LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags
    lv_arc_set_range(ui_pm40Arc, 0, 250);
    lv_arc_set_value(ui_pm40Arc, 70);
    lv_obj_set_style_arc_color(ui_pm40Arc, lv_color_hex(0x707F78), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_pm40Arc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_pm40Arc, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_pm40Arc, lv_color_hex(0xEB8A16), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_pm40Arc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_pm40Arc, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_pm40Arc, lv_color_hex(0xE7B46A), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pm40Arc, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_pm40Arc, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_pm40Arc, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_pm40Arc, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_pm40Arc, 2, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_pm40StateText = lv_label_create(ui_pm40Panel);
    lv_obj_set_width(ui_pm40StateText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pm40StateText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_pm40StateText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pm40StateText, "BAD");
    lv_obj_set_style_text_color(ui_pm40StateText, lv_color_hex(0xEB8A16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pm40StateText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_pm40StateText, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pm40StateText, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pm40ValueText = lv_label_create(ui_pm40Panel);
    lv_obj_set_width(ui_pm40ValueText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pm40ValueText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pm40ValueText, 1);
    lv_obj_set_y(ui_pm40ValueText, 19);
    lv_obj_set_align(ui_pm40ValueText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pm40ValueText, "70");
    lv_obj_set_style_text_color(ui_pm40ValueText, lv_color_hex(0xEB8A16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pm40ValueText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_pm40ValueText, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pm40ValueText, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pm40LabelText = lv_label_create(ui_pm40Panel);
    lv_obj_set_width(ui_pm40LabelText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pm40LabelText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pm40LabelText, 1);
    lv_obj_set_y(ui_pm40LabelText, 32);
    lv_obj_set_align(ui_pm40LabelText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pm40LabelText, "PM 4.0");
    lv_obj_set_style_text_color(ui_pm40LabelText, lv_color_hex(0xEB8A16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pm40LabelText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_pm40LabelText, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pm40LabelText, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pm100Panel = lv_obj_create(ui_pmScreenBackPanel);
    lv_obj_set_width(ui_pm100Panel, 82);
    lv_obj_set_height(ui_pm100Panel, 85);
    lv_obj_set_x(ui_pm100Panel, 67);
    lv_obj_set_y(ui_pm100Panel, 47);
    lv_obj_set_align(ui_pm100Panel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_pm100Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pm100Panel, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pm100Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pm100Arc = lv_arc_create(ui_pm100Panel);
    lv_obj_set_width(ui_pm100Arc, 63);
    lv_obj_set_height(ui_pm100Arc, 64);
    lv_obj_set_align(ui_pm100Arc, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_pm100Arc, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK |
                       LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags
    lv_arc_set_range(ui_pm100Arc, 0, 425);
    lv_arc_set_value(ui_pm100Arc, 355);
    lv_obj_set_style_arc_color(ui_pm100Arc, lv_color_hex(0x707F78), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_pm100Arc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_pm100Arc, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_pm100Arc, lv_color_hex(0xDF1919), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_pm100Arc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_pm100Arc, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_pm100Arc, lv_color_hex(0xD48484), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pm100Arc, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_pm100Arc, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_pm100Arc, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_pm100Arc, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_pm100Arc, 2, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_pm100StateText = lv_label_create(ui_pm100Panel);
    lv_obj_set_width(ui_pm100StateText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pm100StateText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_pm100StateText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pm100StateText, "POOR");
    lv_obj_set_style_text_color(ui_pm100StateText, lv_color_hex(0xDF1919), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pm100StateText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_pm100StateText, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pm100StateText, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pm100ValueText = lv_label_create(ui_pm100Panel);
    lv_obj_set_width(ui_pm100ValueText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pm100ValueText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pm100ValueText, 1);
    lv_obj_set_y(ui_pm100ValueText, 19);
    lv_obj_set_align(ui_pm100ValueText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pm100ValueText, "355");
    lv_obj_set_style_text_color(ui_pm100ValueText, lv_color_hex(0xDF1919), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pm100ValueText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_pm100ValueText, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pm100ValueText, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pm100LabelText = lv_label_create(ui_pm100Panel);
    lv_obj_set_width(ui_pm100LabelText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pm100LabelText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pm100LabelText, 1);
    lv_obj_set_y(ui_pm100LabelText, 32);
    lv_obj_set_align(ui_pm100LabelText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pm100LabelText, "PM 10.0");
    lv_obj_set_style_text_color(ui_pm100LabelText, lv_color_hex(0xDF1919), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pm100LabelText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_pm100LabelText, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pm100LabelText, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_homeButtonPM = lv_button_create(ui_pmScreenBackPanel);
    lv_obj_set_width(ui_homeButtonPM, 30);
    lv_obj_set_height(ui_homeButtonPM, 30);
    lv_obj_set_x(ui_homeButtonPM, 0);
    lv_obj_set_y(ui_homeButtonPM, 77);
    lv_obj_set_align(ui_homeButtonPM, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_homeButtonPM, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_homeButtonPM, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_homeButtonPM, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_homeButtonPM, lv_color_hex(0x7C9EE7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_homeButtonPM, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_homeButtonPM, &ui_img_homeicon_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rightArrowButtonPM = lv_button_create(ui_pmScreen);
    lv_obj_set_width(ui_rightArrowButtonPM, 25);
    lv_obj_set_height(ui_rightArrowButtonPM, 67);
    lv_obj_set_x(ui_rightArrowButtonPM, 144);
    lv_obj_set_y(ui_rightArrowButtonPM, 0);
    lv_obj_set_align(ui_rightArrowButtonPM, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_rightArrowButtonPM, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_rightArrowButtonPM, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_rightArrowButtonPM, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rightArrowButtonPM, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_rightArrowButtonPM, &ui_img_rightarrowicon_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settingsButtonPM = lv_button_create(ui_pmScreen);
    lv_obj_set_width(ui_settingsButtonPM, 34);
    lv_obj_set_height(ui_settingsButtonPM, 30);
    lv_obj_set_x(ui_settingsButtonPM, 140);
    lv_obj_set_y(ui_settingsButtonPM, -101);
    lv_obj_set_align(ui_settingsButtonPM, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_settingsButtonPM, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_settingsButtonPM, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_settingsButtonPM, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_settingsButtonPM, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_settingsButtonPM, &ui_img_settingsicon_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_tempScreenButtonPM, ui_event_tempScreenButtonPM, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_vocScreenButtonPM, ui_event_vocScreenButtonPM, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_co2ScreenButtonPM, ui_event_co2ScreenButtonPM, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_homeButtonPM, ui_event_homeButtonPM, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_rightArrowButtonPM, ui_event_rightArrowButtonPM, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_settingsButtonPM, ui_event_settingsButtonPM, LV_EVENT_ALL, NULL);

}

void ui_pmScreen_screen_destroy(void)
{
    if(ui_pmScreen) lv_obj_del(ui_pmScreen);

    // NULL screen variables
    ui_pmScreen = NULL;
    ui_topPanelPM = NULL;
    ui_pMScreenButtonPM = NULL;
    ui_pMScreenButtonLabel = NULL;
    ui_tempScreenButtonPM = NULL;
    ui_tempScreenButtonLabel = NULL;
    ui_vocScreenButtonPM = NULL;
    ui_vocScreenButtonLabel = NULL;
    ui_co2ScreenButtonPM = NULL;
    ui_co2ScreenButtonLabel = NULL;
    ui_pmScreenBackPanel = NULL;
    ui_pm10Panel = NULL;
    ui_pm10Arc = NULL;
    ui_pm10StateText = NULL;
    ui_pm10ValueText = NULL;
    ui_pm10LabelText = NULL;
    ui_pm25Panel = NULL;
    ui_pm25Arc = NULL;
    ui_pm25StateText = NULL;
    ui_pm25ValueText = NULL;
    ui_pm25LabelText = NULL;
    ui_pm40Panel = NULL;
    ui_pm40Arc = NULL;
    ui_pm40StateText = NULL;
    ui_pm40ValueText = NULL;
    ui_pm40LabelText = NULL;
    ui_pm100Panel = NULL;
    ui_pm100Arc = NULL;
    ui_pm100StateText = NULL;
    ui_pm100ValueText = NULL;
    ui_pm100LabelText = NULL;
    ui_homeButtonPM = NULL;
    ui_rightArrowButtonPM = NULL;
    ui_settingsButtonPM = NULL;

}
