// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: display_screens

#include "ui.h"

lv_obj_t * ui_wifiSelectionScreen = NULL;
lv_obj_t * ui_topPanelWiFiSelectionScreen = NULL;
lv_obj_t * ui_wiFiSelectionScreenButtonWiFi = NULL;
lv_obj_t * ui_wiFiScreenButtonLabelWiFi = NULL;
lv_obj_t * ui_sdScreenButtonWiFi = NULL;
lv_obj_t * ui_sdScreenButtonLabelWiFi = NULL;
lv_obj_t * ui_WiFiSelectionScreenBackPanel = NULL;
lv_obj_t * ui_WiFiSelectionScreenDropdown = NULL;
lv_obj_t * ui_WiFiSelectionScreenPwdInputTextArea = NULL;
lv_obj_t * ui_ConnectedWiFiPanelWiFiSelectionScreen = NULL;
lv_obj_t * ui_ConnectedWiFiNameLabelWiFiSelectionScreen = NULL;
lv_obj_t * ui_ConnectedWiFiStatusLabelWiFiSelectionScreen1 = NULL;
lv_obj_t * ui_ForgetWiFiButtonWiFiSelectionScreen = NULL;
lv_obj_t * ui_ForgetWiFiButtonLabelWiFiSelectionScreen = NULL;
lv_obj_t * ui_homeButtonWiFi = NULL;
lv_obj_t * ui_KeyboardWiFiSelectionScreen = NULL;
lv_obj_t * ui_LoadingPanelWiFiSelectionScreen = NULL;
lv_obj_t * ui_spinnerWiFiSelectionScreen = NULL;
lv_obj_t * ui_FailedConnectionPanelWiFiSelectionScreen = NULL;
lv_obj_t * ui_FailedConnectionLabelWiFiSelectionScreen = NULL;
// event funtions
void ui_event_topPanelWiFiSelectionScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_delete(&ui_wifiSelectionScreen);
    }
}

void ui_event_sdScreenButtonWiFi(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_sdScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_sdScreen_screen_init);
        _ui_screen_delete(&ui_wifiSelectionScreen);
    }
}

void ui_event_WiFiSelectionScreenDropdown(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        setWiFiToDropdown(e);
        _ui_keyboard_set_target(ui_KeyboardWiFiSelectionScreen,  ui_WiFiSelectionScreenPwdInputTextArea);
        _ui_flag_modify(ui_KeyboardWiFiSelectionScreen, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_WiFiSelectionScreenPwdInputTextArea, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_WiFiSelectionScreenPwdInputTextArea(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_KeyboardWiFiSelectionScreen, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}

void ui_event_ForgetWiFiButtonWiFiSelectionScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_ConnectedWiFiPanelWiFiSelectionScreen, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_ForgetWiFiButtonWiFiSelectionScreen, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_homeButtonWiFi(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_airQualityScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_airQualityScreen_screen_init);
        _ui_screen_delete(&ui_wifiSelectionScreen);
    }
}

void ui_event_KeyboardWiFiSelectionScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        _ui_flag_modify(ui_LoadingPanelWiFiSelectionScreen, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_KeyboardWiFiSelectionScreen, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_WiFiSelectionScreenPwdInputTextArea, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        tryConnectingToWiFi();
    }
}

// build funtions

void ui_wifiSelectionScreen_screen_init(void)
{
    ui_wifiSelectionScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_wifiSelectionScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_topPanelWiFiSelectionScreen = lv_obj_create(ui_wifiSelectionScreen);
    lv_obj_set_width(ui_topPanelWiFiSelectionScreen, 327);
    lv_obj_set_height(ui_topPanelWiFiSelectionScreen, 30);
    lv_obj_set_x(ui_topPanelWiFiSelectionScreen, 0);
    lv_obj_set_y(ui_topPanelWiFiSelectionScreen, -100);
    lv_obj_set_align(ui_topPanelWiFiSelectionScreen, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_topPanelWiFiSelectionScreen, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_topPanelWiFiSelectionScreen, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_topPanelWiFiSelectionScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_topPanelWiFiSelectionScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_topPanelWiFiSelectionScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_topPanelWiFiSelectionScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_topPanelWiFiSelectionScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wiFiSelectionScreenButtonWiFi = lv_button_create(ui_topPanelWiFiSelectionScreen);
    lv_obj_set_width(ui_wiFiSelectionScreenButtonWiFi, 58);
    lv_obj_set_height(ui_wiFiSelectionScreenButtonWiFi, 30);
    lv_obj_set_x(ui_wiFiSelectionScreenButtonWiFi, 0);
    lv_obj_set_y(ui_wiFiSelectionScreenButtonWiFi, -37);
    lv_obj_set_align(ui_wiFiSelectionScreenButtonWiFi, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wiFiSelectionScreenButtonWiFi, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_wiFiSelectionScreenButtonWiFi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_wiFiSelectionScreenButtonWiFi, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_wiFiSelectionScreenButtonWiFi, lv_color_hex(0x7C9EE7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_wiFiSelectionScreenButtonWiFi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wiFiScreenButtonLabelWiFi = lv_label_create(ui_wiFiSelectionScreenButtonWiFi);
    lv_obj_set_width(ui_wiFiScreenButtonLabelWiFi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wiFiScreenButtonLabelWiFi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_wiFiScreenButtonLabelWiFi, LV_ALIGN_CENTER);
    lv_label_set_text(ui_wiFiScreenButtonLabelWiFi, "Wi-Fi");
    lv_obj_set_style_text_font(ui_wiFiScreenButtonLabelWiFi, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sdScreenButtonWiFi = lv_button_create(ui_topPanelWiFiSelectionScreen);
    lv_obj_set_width(ui_sdScreenButtonWiFi, 58);
    lv_obj_set_height(ui_sdScreenButtonWiFi, 30);
    lv_obj_set_x(ui_sdScreenButtonWiFi, 0);
    lv_obj_set_y(ui_sdScreenButtonWiFi, -37);
    lv_obj_set_align(ui_sdScreenButtonWiFi, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_sdScreenButtonWiFi, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_sdScreenButtonWiFi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_sdScreenButtonWiFi, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_sdScreenButtonWiFi, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sdScreenButtonWiFi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sdScreenButtonLabelWiFi = lv_label_create(ui_sdScreenButtonWiFi);
    lv_obj_set_width(ui_sdScreenButtonLabelWiFi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sdScreenButtonLabelWiFi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_sdScreenButtonLabelWiFi, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sdScreenButtonLabelWiFi, "SD");
    lv_obj_set_style_text_font(ui_sdScreenButtonLabelWiFi, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WiFiSelectionScreenBackPanel = lv_obj_create(ui_wifiSelectionScreen);
    lv_obj_set_width(ui_WiFiSelectionScreenBackPanel, 267);
    lv_obj_set_height(ui_WiFiSelectionScreenBackPanel, 194);
    lv_obj_set_x(ui_WiFiSelectionScreenBackPanel, 0);
    lv_obj_set_y(ui_WiFiSelectionScreenBackPanel, 19);
    lv_obj_set_align(ui_WiFiSelectionScreenBackPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_WiFiSelectionScreenBackPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_WiFiSelectionScreenBackPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WiFiSelectionScreenBackPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WiFiSelectionScreenBackPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_WiFiSelectionScreenBackPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WiFiSelectionScreenDropdown = lv_dropdown_create(ui_WiFiSelectionScreenBackPanel);
    lv_dropdown_set_text(ui_WiFiSelectionScreenDropdown, "Select Wi-Fi");
    lv_obj_set_width(ui_WiFiSelectionScreenDropdown, 255);
    lv_obj_set_height(ui_WiFiSelectionScreenDropdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WiFiSelectionScreenDropdown, 0);
    lv_obj_set_y(ui_WiFiSelectionScreenDropdown, -75);
    lv_obj_set_align(ui_WiFiSelectionScreenDropdown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WiFiSelectionScreenDropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_WiFiSelectionScreenDropdown, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_WiFiSelectionScreenDropdown, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_WiFiSelectionScreenDropdown, &lv_font_montserrat_12,
                               LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_WiFiSelectionScreenDropdown), &lv_font_montserrat_12,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(lv_dropdown_get_list(ui_WiFiSelectionScreenDropdown), 0,
                                  LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_WiFiSelectionScreenDropdown), &lv_font_montserrat_12,
                               LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_WiFiSelectionScreenPwdInputTextArea = lv_textarea_create(ui_WiFiSelectionScreenBackPanel);
    lv_obj_set_width(ui_WiFiSelectionScreenPwdInputTextArea, 150);
    lv_obj_set_height(ui_WiFiSelectionScreenPwdInputTextArea, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_WiFiSelectionScreenPwdInputTextArea, 0);
    lv_obj_set_y(ui_WiFiSelectionScreenPwdInputTextArea, -28);
    lv_obj_set_align(ui_WiFiSelectionScreenPwdInputTextArea, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_WiFiSelectionScreenPwdInputTextArea, "Password");
    lv_textarea_set_one_line(ui_WiFiSelectionScreenPwdInputTextArea, true);
    lv_obj_add_flag(ui_WiFiSelectionScreenPwdInputTextArea, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_WiFiSelectionScreenPwdInputTextArea, &lv_font_montserrat_12,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_WiFiSelectionScreenPwdInputTextArea, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_width(ui_WiFiSelectionScreenPwdInputTextArea, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_WiFiSelectionScreenPwdInputTextArea, &lv_font_montserrat_12,
                               LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);

    ui_ConnectedWiFiPanelWiFiSelectionScreen = lv_obj_create(ui_WiFiSelectionScreenBackPanel);
    lv_obj_set_width(ui_ConnectedWiFiPanelWiFiSelectionScreen, 267);
    lv_obj_set_height(ui_ConnectedWiFiPanelWiFiSelectionScreen, 30);
    lv_obj_set_x(ui_ConnectedWiFiPanelWiFiSelectionScreen, 0);
    lv_obj_set_y(ui_ConnectedWiFiPanelWiFiSelectionScreen, -25);
    lv_obj_set_align(ui_ConnectedWiFiPanelWiFiSelectionScreen, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ConnectedWiFiPanelWiFiSelectionScreen, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_ConnectedWiFiPanelWiFiSelectionScreen,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_radius(ui_ConnectedWiFiPanelWiFiSelectionScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ConnectedWiFiPanelWiFiSelectionScreen, lv_color_hex(0x7C9EE7),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ConnectedWiFiPanelWiFiSelectionScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ConnectedWiFiPanelWiFiSelectionScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConnectedWiFiNameLabelWiFiSelectionScreen = lv_label_create(ui_ConnectedWiFiPanelWiFiSelectionScreen);
    lv_obj_set_width(ui_ConnectedWiFiNameLabelWiFiSelectionScreen, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ConnectedWiFiNameLabelWiFiSelectionScreen, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ConnectedWiFiNameLabelWiFiSelectionScreen, -62);
    lv_obj_set_y(ui_ConnectedWiFiNameLabelWiFiSelectionScreen, -1);
    lv_obj_set_align(ui_ConnectedWiFiNameLabelWiFiSelectionScreen, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ConnectedWiFiNameLabelWiFiSelectionScreen, "Connected Wi-Fi");
    lv_obj_set_style_text_font(ui_ConnectedWiFiNameLabelWiFiSelectionScreen, &lv_font_montserrat_12,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConnectedWiFiStatusLabelWiFiSelectionScreen1 = lv_label_create(ui_ConnectedWiFiPanelWiFiSelectionScreen);
    lv_obj_set_width(ui_ConnectedWiFiStatusLabelWiFiSelectionScreen1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ConnectedWiFiStatusLabelWiFiSelectionScreen1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ConnectedWiFiStatusLabelWiFiSelectionScreen1, 85);
    lv_obj_set_y(ui_ConnectedWiFiStatusLabelWiFiSelectionScreen1, 0);
    lv_obj_set_align(ui_ConnectedWiFiStatusLabelWiFiSelectionScreen1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ConnectedWiFiStatusLabelWiFiSelectionScreen1, "Connected");
    lv_obj_set_style_text_font(ui_ConnectedWiFiStatusLabelWiFiSelectionScreen1, &lv_font_montserrat_12,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ForgetWiFiButtonWiFiSelectionScreen = lv_button_create(ui_WiFiSelectionScreenBackPanel);
    lv_obj_set_width(ui_ForgetWiFiButtonWiFiSelectionScreen, 85);
    lv_obj_set_height(ui_ForgetWiFiButtonWiFiSelectionScreen, 30);
    lv_obj_set_x(ui_ForgetWiFiButtonWiFiSelectionScreen, -1);
    lv_obj_set_y(ui_ForgetWiFiButtonWiFiSelectionScreen, 21);
    lv_obj_set_align(ui_ForgetWiFiButtonWiFiSelectionScreen, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ForgetWiFiButtonWiFiSelectionScreen, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ForgetWiFiButtonWiFiSelectionScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ForgetWiFiButtonWiFiSelectionScreen, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ForgetWiFiButtonWiFiSelectionScreen, lv_color_hex(0x7C9EE7),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ForgetWiFiButtonWiFiSelectionScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ForgetWiFiButtonLabelWiFiSelectionScreen = lv_label_create(ui_ForgetWiFiButtonWiFiSelectionScreen);
    lv_obj_set_width(ui_ForgetWiFiButtonLabelWiFiSelectionScreen, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ForgetWiFiButtonLabelWiFiSelectionScreen, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ForgetWiFiButtonLabelWiFiSelectionScreen, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ForgetWiFiButtonLabelWiFiSelectionScreen, "Forget Wi-Fi");
    lv_obj_set_style_text_font(ui_ForgetWiFiButtonLabelWiFiSelectionScreen, &lv_font_montserrat_12,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_homeButtonWiFi = lv_button_create(ui_WiFiSelectionScreenBackPanel);
    lv_obj_set_width(ui_homeButtonWiFi, 30);
    lv_obj_set_height(ui_homeButtonWiFi, 30);
    lv_obj_set_x(ui_homeButtonWiFi, 0);
    lv_obj_set_y(ui_homeButtonWiFi, 77);
    lv_obj_set_align(ui_homeButtonWiFi, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_homeButtonWiFi, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_homeButtonWiFi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_homeButtonWiFi, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_homeButtonWiFi, lv_color_hex(0x7C9EE7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_homeButtonWiFi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_homeButtonWiFi, &ui_img_homeicon_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_KeyboardWiFiSelectionScreen = lv_keyboard_create(ui_wifiSelectionScreen);
    lv_obj_set_width(ui_KeyboardWiFiSelectionScreen, 320);
    lv_obj_set_height(ui_KeyboardWiFiSelectionScreen, 100);
    lv_obj_set_x(ui_KeyboardWiFiSelectionScreen, 0);
    lv_obj_set_y(ui_KeyboardWiFiSelectionScreen, 70);
    lv_obj_set_align(ui_KeyboardWiFiSelectionScreen, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_KeyboardWiFiSelectionScreen, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_LoadingPanelWiFiSelectionScreen = lv_obj_create(ui_wifiSelectionScreen);
    lv_obj_set_width(ui_LoadingPanelWiFiSelectionScreen, 320);
    lv_obj_set_height(ui_LoadingPanelWiFiSelectionScreen, 240);
    lv_obj_set_align(ui_LoadingPanelWiFiSelectionScreen, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LoadingPanelWiFiSelectionScreen, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_LoadingPanelWiFiSelectionScreen,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_radius(ui_LoadingPanelWiFiSelectionScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LoadingPanelWiFiSelectionScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LoadingPanelWiFiSelectionScreen, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_LoadingPanelWiFiSelectionScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_spinnerWiFiSelectionScreen = lv_spinner_create(ui_LoadingPanelWiFiSelectionScreen);
    //lv_spinner_set_anim_params(ui_spinnerWiFiSelectionScreen, 1000, 90);
    lv_obj_set_width(ui_spinnerWiFiSelectionScreen, 50);
    lv_obj_set_height(ui_spinnerWiFiSelectionScreen, 50);
    lv_obj_set_align(ui_spinnerWiFiSelectionScreen, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_spinnerWiFiSelectionScreen, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_arc_color(ui_spinnerWiFiSelectionScreen, lv_color_hex(0x707F78), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_spinnerWiFiSelectionScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_spinnerWiFiSelectionScreen, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_spinnerWiFiSelectionScreen, lv_color_hex(0x7C9EE7), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_spinnerWiFiSelectionScreen, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_spinnerWiFiSelectionScreen, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_FailedConnectionPanelWiFiSelectionScreen = lv_obj_create(ui_wifiSelectionScreen);
    lv_obj_set_width(ui_FailedConnectionPanelWiFiSelectionScreen, 320);
    lv_obj_set_height(ui_FailedConnectionPanelWiFiSelectionScreen, 240);
    lv_obj_set_align(ui_FailedConnectionPanelWiFiSelectionScreen, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_FailedConnectionPanelWiFiSelectionScreen, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_FailedConnectionPanelWiFiSelectionScreen,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_radius(ui_FailedConnectionPanelWiFiSelectionScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_FailedConnectionPanelWiFiSelectionScreen, lv_color_hex(0x000000),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_FailedConnectionPanelWiFiSelectionScreen, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_FailedConnectionPanelWiFiSelectionScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FailedConnectionLabelWiFiSelectionScreen = lv_label_create(ui_FailedConnectionPanelWiFiSelectionScreen);
    lv_obj_set_width(ui_FailedConnectionLabelWiFiSelectionScreen, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FailedConnectionLabelWiFiSelectionScreen, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_FailedConnectionLabelWiFiSelectionScreen, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FailedConnectionLabelWiFiSelectionScreen, "Failed to connect!!");

    lv_obj_add_event_cb(ui_sdScreenButtonWiFi, ui_event_sdScreenButtonWiFi, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_topPanelWiFiSelectionScreen, ui_event_topPanelWiFiSelectionScreen, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_WiFiSelectionScreenDropdown, ui_event_WiFiSelectionScreenDropdown, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_WiFiSelectionScreenPwdInputTextArea, ui_event_WiFiSelectionScreenPwdInputTextArea, LV_EVENT_ALL,
                        NULL);
    lv_obj_add_event_cb(ui_ForgetWiFiButtonWiFiSelectionScreen, ui_event_ForgetWiFiButtonWiFiSelectionScreen, LV_EVENT_ALL,
                        NULL);
    lv_obj_add_event_cb(ui_homeButtonWiFi, ui_event_homeButtonWiFi, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_KeyboardWiFiSelectionScreen, ui_event_KeyboardWiFiSelectionScreen, LV_EVENT_ALL, NULL);

}

void ui_wifiSelectionScreen_screen_destroy(void)
{
    if(ui_wifiSelectionScreen) lv_obj_del(ui_wifiSelectionScreen);

    // NULL screen variables
    ui_wifiSelectionScreen = NULL;
    ui_topPanelWiFiSelectionScreen = NULL;
    ui_wiFiSelectionScreenButtonWiFi = NULL;
    ui_wiFiScreenButtonLabelWiFi = NULL;
    ui_sdScreenButtonWiFi = NULL;
    ui_sdScreenButtonLabelWiFi = NULL;
    ui_WiFiSelectionScreenBackPanel = NULL;
    ui_WiFiSelectionScreenDropdown = NULL;
    ui_WiFiSelectionScreenPwdInputTextArea = NULL;
    ui_ConnectedWiFiPanelWiFiSelectionScreen = NULL;
    ui_ConnectedWiFiNameLabelWiFiSelectionScreen = NULL;
    ui_ConnectedWiFiStatusLabelWiFiSelectionScreen1 = NULL;
    ui_ForgetWiFiButtonWiFiSelectionScreen = NULL;
    ui_ForgetWiFiButtonLabelWiFiSelectionScreen = NULL;
    ui_homeButtonWiFi = NULL;
    ui_KeyboardWiFiSelectionScreen = NULL;
    ui_LoadingPanelWiFiSelectionScreen = NULL;
    ui_spinnerWiFiSelectionScreen = NULL;
    ui_FailedConnectionPanelWiFiSelectionScreen = NULL;
    ui_FailedConnectionLabelWiFiSelectionScreen = NULL;

}
