// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: display_screens

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void setWiFiToDropdown(lv_event_t * e);
void tryConnectingToWiFi();

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
