// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: display_screens

#include "ui.h"

lv_obj_t * ui_sdScreen = NULL;
lv_obj_t * ui_topPanelSdScreen = NULL;
lv_obj_t * ui_wiFiSelectionScreenButtonSd = NULL;
lv_obj_t * ui_wiFiScreenButtonLabelWiFi1 = NULL;
lv_obj_t * ui_sdScreenButtonSd = NULL;
lv_obj_t * ui_sdScreenButtonLabelWiFi1 = NULL;
lv_obj_t * ui_SdScreenBackPanel = NULL;
lv_obj_t * ui_sdSpaceBarPanelSdScreen = NULL;
lv_obj_t * ui_sdSpaceBarLabelSdScreen = NULL;
lv_obj_t * ui_sdSpaceImageSdScreen = NULL;
lv_obj_t * ui_homeButtonSd = NULL;
// event funtions
void ui_event_topPanelSdScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_delete(&ui_sdScreen);
    }
}

void ui_event_wiFiSelectionScreenButtonSd(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_wifiSelectionScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_wifiSelectionScreen_screen_init);
        _ui_screen_delete(&ui_sdScreen);
    }
}

void ui_event_homeButtonSd(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_airQualityScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_airQualityScreen_screen_init);
        _ui_screen_delete(&ui_sdScreen);
    }
}

// build funtions

void ui_sdScreen_screen_init(void)
{
    ui_sdScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_sdScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_topPanelSdScreen = lv_obj_create(ui_sdScreen);
    lv_obj_set_width(ui_topPanelSdScreen, 327);
    lv_obj_set_height(ui_topPanelSdScreen, 30);
    lv_obj_set_x(ui_topPanelSdScreen, 0);
    lv_obj_set_y(ui_topPanelSdScreen, -100);
    lv_obj_set_align(ui_topPanelSdScreen, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_topPanelSdScreen, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_topPanelSdScreen, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_topPanelSdScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_topPanelSdScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_topPanelSdScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_topPanelSdScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_topPanelSdScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wiFiSelectionScreenButtonSd = lv_button_create(ui_topPanelSdScreen);
    lv_obj_set_width(ui_wiFiSelectionScreenButtonSd, 58);
    lv_obj_set_height(ui_wiFiSelectionScreenButtonSd, 30);
    lv_obj_set_x(ui_wiFiSelectionScreenButtonSd, 0);
    lv_obj_set_y(ui_wiFiSelectionScreenButtonSd, -37);
    lv_obj_set_align(ui_wiFiSelectionScreenButtonSd, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wiFiSelectionScreenButtonSd, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_wiFiSelectionScreenButtonSd, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_wiFiSelectionScreenButtonSd, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_wiFiSelectionScreenButtonSd, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_wiFiSelectionScreenButtonSd, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wiFiScreenButtonLabelWiFi1 = lv_label_create(ui_wiFiSelectionScreenButtonSd);
    lv_obj_set_width(ui_wiFiScreenButtonLabelWiFi1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wiFiScreenButtonLabelWiFi1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_wiFiScreenButtonLabelWiFi1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_wiFiScreenButtonLabelWiFi1, "Wi-Fi");
    lv_obj_set_style_text_font(ui_wiFiScreenButtonLabelWiFi1, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sdScreenButtonSd = lv_button_create(ui_topPanelSdScreen);
    lv_obj_set_width(ui_sdScreenButtonSd, 58);
    lv_obj_set_height(ui_sdScreenButtonSd, 30);
    lv_obj_set_x(ui_sdScreenButtonSd, 0);
    lv_obj_set_y(ui_sdScreenButtonSd, -37);
    lv_obj_set_align(ui_sdScreenButtonSd, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_sdScreenButtonSd, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_sdScreenButtonSd, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_sdScreenButtonSd, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_sdScreenButtonSd, lv_color_hex(0x7C9EE7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sdScreenButtonSd, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sdScreenButtonLabelWiFi1 = lv_label_create(ui_sdScreenButtonSd);
    lv_obj_set_width(ui_sdScreenButtonLabelWiFi1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sdScreenButtonLabelWiFi1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_sdScreenButtonLabelWiFi1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sdScreenButtonLabelWiFi1, "SD");
    lv_obj_set_style_text_font(ui_sdScreenButtonLabelWiFi1, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SdScreenBackPanel = lv_obj_create(ui_sdScreen);
    lv_obj_set_width(ui_SdScreenBackPanel, 267);
    lv_obj_set_height(ui_SdScreenBackPanel, 194);
    lv_obj_set_x(ui_SdScreenBackPanel, 0);
    lv_obj_set_y(ui_SdScreenBackPanel, 19);
    lv_obj_set_align(ui_SdScreenBackPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SdScreenBackPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SdScreenBackPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SdScreenBackPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SdScreenBackPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SdScreenBackPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sdSpaceBarPanelSdScreen = lv_obj_create(ui_SdScreenBackPanel);
    lv_obj_set_width(ui_sdSpaceBarPanelSdScreen, 267);
    lv_obj_set_height(ui_sdSpaceBarPanelSdScreen, 30);
    lv_obj_set_x(ui_sdSpaceBarPanelSdScreen, 0);
    lv_obj_set_y(ui_sdSpaceBarPanelSdScreen, -25);
    lv_obj_set_align(ui_sdSpaceBarPanelSdScreen, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_sdSpaceBarPanelSdScreen,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_radius(ui_sdSpaceBarPanelSdScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_sdSpaceBarPanelSdScreen, lv_color_hex(0x7C9EE7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sdSpaceBarPanelSdScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_sdSpaceBarPanelSdScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sdSpaceBarLabelSdScreen = lv_label_create(ui_sdSpaceBarPanelSdScreen);
    lv_obj_set_width(ui_sdSpaceBarLabelSdScreen, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sdSpaceBarLabelSdScreen, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sdSpaceBarLabelSdScreen, -62);
    lv_obj_set_y(ui_sdSpaceBarLabelSdScreen, -1);
    lv_obj_set_align(ui_sdSpaceBarLabelSdScreen, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sdSpaceBarLabelSdScreen, "SD card name");
    lv_obj_set_style_text_font(ui_sdSpaceBarLabelSdScreen, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sdSpaceImageSdScreen = lv_label_create(ui_sdSpaceBarPanelSdScreen);
    lv_obj_set_width(ui_sdSpaceImageSdScreen, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sdSpaceImageSdScreen, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sdSpaceImageSdScreen, 85);
    lv_obj_set_y(ui_sdSpaceImageSdScreen, 0);
    lv_obj_set_align(ui_sdSpaceImageSdScreen, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sdSpaceImageSdScreen, "Storage left");
    lv_obj_set_style_text_font(ui_sdSpaceImageSdScreen, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_homeButtonSd = lv_button_create(ui_SdScreenBackPanel);
    lv_obj_set_width(ui_homeButtonSd, 30);
    lv_obj_set_height(ui_homeButtonSd, 30);
    lv_obj_set_x(ui_homeButtonSd, 0);
    lv_obj_set_y(ui_homeButtonSd, 77);
    lv_obj_set_align(ui_homeButtonSd, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_homeButtonSd, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_homeButtonSd, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_homeButtonSd, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_homeButtonSd, lv_color_hex(0x7C9EE7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_homeButtonSd, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_homeButtonSd, &ui_img_homeicon_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_wiFiSelectionScreenButtonSd, ui_event_wiFiSelectionScreenButtonSd, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_topPanelSdScreen, ui_event_topPanelSdScreen, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_homeButtonSd, ui_event_homeButtonSd, LV_EVENT_ALL, NULL);

}

void ui_sdScreen_screen_destroy(void)
{
    if(ui_sdScreen) lv_obj_del(ui_sdScreen);

    // NULL screen variables
    ui_sdScreen = NULL;
    ui_topPanelSdScreen = NULL;
    ui_wiFiSelectionScreenButtonSd = NULL;
    ui_wiFiScreenButtonLabelWiFi1 = NULL;
    ui_sdScreenButtonSd = NULL;
    ui_sdScreenButtonLabelWiFi1 = NULL;
    ui_SdScreenBackPanel = NULL;
    ui_sdSpaceBarPanelSdScreen = NULL;
    ui_sdSpaceBarLabelSdScreen = NULL;
    ui_sdSpaceImageSdScreen = NULL;
    ui_homeButtonSd = NULL;

}
