// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: display_screens

#ifndef UI_SDSCREEN_H
#define UI_SDSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_sdScreen
extern void ui_sdScreen_screen_init(void);
extern void ui_sdScreen_screen_destroy(void);
extern lv_obj_t * ui_sdScreen;
extern void ui_event_topPanelSdScreen(lv_event_t * e);
extern lv_obj_t * ui_topPanelSdScreen;
extern void ui_event_wiFiSelectionScreenButtonSd(lv_event_t * e);
extern lv_obj_t * ui_wiFiSelectionScreenButtonSd;
extern lv_obj_t * ui_wiFiScreenButtonLabelWiFi1;
extern lv_obj_t * ui_sdScreenButtonSd;
extern lv_obj_t * ui_sdScreenButtonLabelWiFi1;
extern lv_obj_t * ui_SdScreenBackPanel;
extern lv_obj_t * ui_sdSpaceBarPanelSdScreen;
extern lv_obj_t * ui_sdSpaceBarLabelSdScreen;
extern lv_obj_t * ui_sdSpaceImageSdScreen;
extern void ui_event_homeButtonSd(lv_event_t * e);
extern lv_obj_t * ui_homeButtonSd;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

