// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: display_screens

#include "ui.h"

lv_obj_t * ui_vocScreen = NULL;
lv_obj_t * ui_topPanelVoc = NULL;
lv_obj_t * ui_pMScreenButtonVoc = NULL;
lv_obj_t * ui_pMScreenButtonLabelVoc = NULL;
lv_obj_t * ui_tempScreenButtonVoc = NULL;
lv_obj_t * ui_tempScreenButtonLabelVoc = NULL;
lv_obj_t * ui_vocScreenButtonVoc = NULL;
lv_obj_t * ui_vocScreenButtonLabelVoc = NULL;
lv_obj_t * ui_co2ScreenButtonVoc = NULL;
lv_obj_t * ui_co2ScreenButtonLabelVoc = NULL;
lv_obj_t * ui_vocScreenBackPanel = NULL;
lv_obj_t * ui_vocPanel = NULL;
lv_obj_t * ui_vocArc = NULL;
lv_obj_t * ui_vocStateText = NULL;
lv_obj_t * ui_vocValueText = NULL;
lv_obj_t * ui_vocLabelText = NULL;
lv_obj_t * ui_noxPanel = NULL;
lv_obj_t * ui_noxArc = NULL;
lv_obj_t * ui_noxStateText = NULL;
lv_obj_t * ui_noxValueText = NULL;
lv_obj_t * ui_noxLabelText = NULL;
lv_obj_t * ui_homeButtonVoc = NULL;
lv_obj_t * ui_settingsButtonVoc = NULL;
lv_obj_t * ui_rightArrowButtonVoc = NULL;
lv_obj_t * ui_leftArrowButtonTemp2 = NULL;
// event funtions
void ui_event_pMScreenButtonVoc(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_pmScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_pmScreen_screen_init);
        _ui_screen_delete(&ui_vocScreen);
    }
}

void ui_event_tempScreenButtonVoc(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_tempScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_tempScreen_screen_init);
        _ui_screen_delete(&ui_vocScreen);
    }
}

void ui_event_co2ScreenButtonVoc(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_co2Screen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_co2Screen_screen_init);
        _ui_screen_delete(&ui_vocScreen);
    }
}

void ui_event_homeButtonVoc(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_airQualityScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_airQualityScreen_screen_init);
        _ui_screen_delete(&ui_vocScreen);
    }
}

void ui_event_settingsButtonVoc(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_wifiSelectionScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_wifiSelectionScreen_screen_init);
        _ui_screen_delete(&ui_vocScreen);
    }
}

void ui_event_rightArrowButtonVoc(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_co2Screen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_co2Screen_screen_init);
        _ui_screen_delete(&ui_vocScreen);
    }
}

void ui_event_leftArrowButtonTemp2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_tempScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_tempScreen_screen_init);
        _ui_screen_delete(&ui_vocScreen);
    }
}

// build funtions

void ui_vocScreen_screen_init(void)
{
    ui_vocScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_vocScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_topPanelVoc = lv_obj_create(ui_vocScreen);
    lv_obj_set_width(ui_topPanelVoc, 327);
    lv_obj_set_height(ui_topPanelVoc, 30);
    lv_obj_set_x(ui_topPanelVoc, 0);
    lv_obj_set_y(ui_topPanelVoc, -100);
    lv_obj_set_align(ui_topPanelVoc, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_topPanelVoc, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_topPanelVoc, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_topPanelVoc, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_topPanelVoc, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_topPanelVoc, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_topPanelVoc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_topPanelVoc, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pMScreenButtonVoc = lv_button_create(ui_topPanelVoc);
    lv_obj_set_width(ui_pMScreenButtonVoc, 58);
    lv_obj_set_height(ui_pMScreenButtonVoc, 30);
    lv_obj_set_x(ui_pMScreenButtonVoc, 0);
    lv_obj_set_y(ui_pMScreenButtonVoc, -37);
    lv_obj_set_align(ui_pMScreenButtonVoc, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pMScreenButtonVoc, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_pMScreenButtonVoc, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pMScreenButtonVoc, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pMScreenButtonVoc, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pMScreenButtonVoc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pMScreenButtonLabelVoc = lv_label_create(ui_pMScreenButtonVoc);
    lv_obj_set_width(ui_pMScreenButtonLabelVoc, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pMScreenButtonLabelVoc, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_pMScreenButtonLabelVoc, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pMScreenButtonLabelVoc, "PM");
    lv_obj_set_style_text_font(ui_pMScreenButtonLabelVoc, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempScreenButtonVoc = lv_button_create(ui_topPanelVoc);
    lv_obj_set_width(ui_tempScreenButtonVoc, 58);
    lv_obj_set_height(ui_tempScreenButtonVoc, 30);
    lv_obj_set_x(ui_tempScreenButtonVoc, 0);
    lv_obj_set_y(ui_tempScreenButtonVoc, -37);
    lv_obj_set_align(ui_tempScreenButtonVoc, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_tempScreenButtonVoc, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_tempScreenButtonVoc, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_tempScreenButtonVoc, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_tempScreenButtonVoc, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_tempScreenButtonVoc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempScreenButtonLabelVoc = lv_label_create(ui_tempScreenButtonVoc);
    lv_obj_set_width(ui_tempScreenButtonLabelVoc, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tempScreenButtonLabelVoc, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_tempScreenButtonLabelVoc, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tempScreenButtonLabelVoc, "TEMP");
    lv_obj_set_style_text_font(ui_tempScreenButtonLabelVoc, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_vocScreenButtonVoc = lv_button_create(ui_topPanelVoc);
    lv_obj_set_width(ui_vocScreenButtonVoc, 58);
    lv_obj_set_height(ui_vocScreenButtonVoc, 30);
    lv_obj_set_x(ui_vocScreenButtonVoc, 0);
    lv_obj_set_y(ui_vocScreenButtonVoc, -37);
    lv_obj_set_align(ui_vocScreenButtonVoc, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_vocScreenButtonVoc, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_vocScreenButtonVoc, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_vocScreenButtonVoc, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_vocScreenButtonVoc, lv_color_hex(0x7C9EE7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_vocScreenButtonVoc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_vocScreenButtonLabelVoc = lv_label_create(ui_vocScreenButtonVoc);
    lv_obj_set_width(ui_vocScreenButtonLabelVoc, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_vocScreenButtonLabelVoc, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_vocScreenButtonLabelVoc, LV_ALIGN_CENTER);
    lv_label_set_text(ui_vocScreenButtonLabelVoc, "VOC");
    lv_obj_set_style_text_font(ui_vocScreenButtonLabelVoc, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_co2ScreenButtonVoc = lv_button_create(ui_topPanelVoc);
    lv_obj_set_width(ui_co2ScreenButtonVoc, 58);
    lv_obj_set_height(ui_co2ScreenButtonVoc, 30);
    lv_obj_set_x(ui_co2ScreenButtonVoc, 0);
    lv_obj_set_y(ui_co2ScreenButtonVoc, -37);
    lv_obj_set_align(ui_co2ScreenButtonVoc, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_co2ScreenButtonVoc, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_co2ScreenButtonVoc, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_co2ScreenButtonVoc, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_co2ScreenButtonVoc, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_co2ScreenButtonVoc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_co2ScreenButtonLabelVoc = lv_label_create(ui_co2ScreenButtonVoc);
    lv_obj_set_width(ui_co2ScreenButtonLabelVoc, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_co2ScreenButtonLabelVoc, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_co2ScreenButtonLabelVoc, LV_ALIGN_CENTER);
    lv_label_set_text(ui_co2ScreenButtonLabelVoc, "CO2");
    lv_obj_set_style_text_font(ui_co2ScreenButtonLabelVoc, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_vocScreenBackPanel = lv_obj_create(ui_vocScreen);
    lv_obj_set_width(ui_vocScreenBackPanel, 267);
    lv_obj_set_height(ui_vocScreenBackPanel, 194);
    lv_obj_set_x(ui_vocScreenBackPanel, 0);
    lv_obj_set_y(ui_vocScreenBackPanel, 19);
    lv_obj_set_align(ui_vocScreenBackPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_vocScreenBackPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_vocScreenBackPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_vocScreenBackPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_vocScreenBackPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_vocScreenBackPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_vocPanel = lv_obj_create(ui_vocScreenBackPanel);
    lv_obj_set_width(ui_vocPanel, 82);
    lv_obj_set_height(ui_vocPanel, 85);
    lv_obj_set_x(ui_vocPanel, -64);
    lv_obj_set_y(ui_vocPanel, -15);
    lv_obj_set_align(ui_vocPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_vocPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_vocPanel, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_vocPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_vocArc = lv_arc_create(ui_vocPanel);
    lv_obj_set_width(ui_vocArc, 63);
    lv_obj_set_height(ui_vocArc, 64);
    lv_obj_set_align(ui_vocArc, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_vocArc, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK |
                       LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags
    lv_arc_set_range(ui_vocArc, 0, 500);
    lv_arc_set_value(ui_vocArc, 100);
    lv_obj_set_style_arc_color(ui_vocArc, lv_color_hex(0x707F78), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_vocArc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_vocArc, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_vocArc, lv_color_hex(0xDADA12), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_vocArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_vocArc, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_vocArc, lv_color_hex(0xDDDDA5), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_vocArc, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_vocArc, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_vocArc, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_vocArc, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_vocArc, 2, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_vocStateText = lv_label_create(ui_vocPanel);
    lv_obj_set_width(ui_vocStateText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_vocStateText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_vocStateText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_vocStateText, "FAIR");
    lv_obj_set_style_text_color(ui_vocStateText, lv_color_hex(0xDADA12), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_vocStateText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_vocStateText, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_vocStateText, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_vocValueText = lv_label_create(ui_vocPanel);
    lv_obj_set_width(ui_vocValueText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_vocValueText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_vocValueText, 1);
    lv_obj_set_y(ui_vocValueText, 19);
    lv_obj_set_align(ui_vocValueText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_vocValueText, "100");
    lv_obj_set_style_text_color(ui_vocValueText, lv_color_hex(0xDADA12), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_vocValueText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_vocValueText, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_vocValueText, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_vocLabelText = lv_label_create(ui_vocPanel);
    lv_obj_set_width(ui_vocLabelText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_vocLabelText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_vocLabelText, 1);
    lv_obj_set_y(ui_vocLabelText, 32);
    lv_obj_set_align(ui_vocLabelText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_vocLabelText, "VOC");
    lv_obj_set_style_text_color(ui_vocLabelText, lv_color_hex(0xDADA12), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_vocLabelText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_vocLabelText, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_vocLabelText, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_noxPanel = lv_obj_create(ui_vocScreenBackPanel);
    lv_obj_set_width(ui_noxPanel, 82);
    lv_obj_set_height(ui_noxPanel, 85);
    lv_obj_set_x(ui_noxPanel, 64);
    lv_obj_set_y(ui_noxPanel, -15);
    lv_obj_set_align(ui_noxPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_noxPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_noxPanel, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_noxPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_noxArc = lv_arc_create(ui_noxPanel);
    lv_obj_set_width(ui_noxArc, 63);
    lv_obj_set_height(ui_noxArc, 64);
    lv_obj_set_align(ui_noxArc, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_noxArc, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK |
                       LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags
    lv_arc_set_range(ui_noxArc, 0, 500);
    lv_arc_set_value(ui_noxArc, 300);
    lv_obj_set_style_arc_color(ui_noxArc, lv_color_hex(0x707F78), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_noxArc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_noxArc, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_noxArc, lv_color_hex(0xEB8A16), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_noxArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_noxArc, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_noxArc, lv_color_hex(0xE7B46A), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_noxArc, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_noxArc, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_noxArc, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_noxArc, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_noxArc, 2, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_noxStateText = lv_label_create(ui_noxPanel);
    lv_obj_set_width(ui_noxStateText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_noxStateText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_noxStateText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_noxStateText, "BAD");
    lv_obj_set_style_text_color(ui_noxStateText, lv_color_hex(0xEB8A16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_noxStateText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_noxStateText, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_noxStateText, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_noxValueText = lv_label_create(ui_noxPanel);
    lv_obj_set_width(ui_noxValueText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_noxValueText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_noxValueText, 1);
    lv_obj_set_y(ui_noxValueText, 19);
    lv_obj_set_align(ui_noxValueText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_noxValueText, "300");
    lv_obj_set_style_text_color(ui_noxValueText, lv_color_hex(0xEB8A16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_noxValueText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_noxValueText, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_noxValueText, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_noxLabelText = lv_label_create(ui_noxPanel);
    lv_obj_set_width(ui_noxLabelText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_noxLabelText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_noxLabelText, 1);
    lv_obj_set_y(ui_noxLabelText, 32);
    lv_obj_set_align(ui_noxLabelText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_noxLabelText, "NOx");
    lv_obj_set_style_text_color(ui_noxLabelText, lv_color_hex(0xEB8A16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_noxLabelText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_noxLabelText, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_noxLabelText, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_homeButtonVoc = lv_button_create(ui_vocScreenBackPanel);
    lv_obj_set_width(ui_homeButtonVoc, 30);
    lv_obj_set_height(ui_homeButtonVoc, 30);
    lv_obj_set_x(ui_homeButtonVoc, 0);
    lv_obj_set_y(ui_homeButtonVoc, 77);
    lv_obj_set_align(ui_homeButtonVoc, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_homeButtonVoc, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_homeButtonVoc, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_homeButtonVoc, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_homeButtonVoc, lv_color_hex(0x7C9EE7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_homeButtonVoc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_homeButtonVoc, &ui_img_homeicon_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settingsButtonVoc = lv_button_create(ui_vocScreen);
    lv_obj_set_width(ui_settingsButtonVoc, 34);
    lv_obj_set_height(ui_settingsButtonVoc, 30);
    lv_obj_set_x(ui_settingsButtonVoc, 140);
    lv_obj_set_y(ui_settingsButtonVoc, -101);
    lv_obj_set_align(ui_settingsButtonVoc, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_settingsButtonVoc, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_settingsButtonVoc, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_settingsButtonVoc, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_settingsButtonVoc, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_settingsButtonVoc, &ui_img_settingsicon_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rightArrowButtonVoc = lv_button_create(ui_vocScreen);
    lv_obj_set_width(ui_rightArrowButtonVoc, 25);
    lv_obj_set_height(ui_rightArrowButtonVoc, 67);
    lv_obj_set_x(ui_rightArrowButtonVoc, 144);
    lv_obj_set_y(ui_rightArrowButtonVoc, 0);
    lv_obj_set_align(ui_rightArrowButtonVoc, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_rightArrowButtonVoc, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_rightArrowButtonVoc, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_rightArrowButtonVoc, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rightArrowButtonVoc, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_rightArrowButtonVoc, &ui_img_rightarrowicon_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_leftArrowButtonTemp2 = lv_button_create(ui_vocScreen);
    lv_obj_set_width(ui_leftArrowButtonTemp2, 28);
    lv_obj_set_height(ui_leftArrowButtonTemp2, 67);
    lv_obj_set_x(ui_leftArrowButtonTemp2, -138);
    lv_obj_set_y(ui_leftArrowButtonTemp2, 0);
    lv_obj_set_align(ui_leftArrowButtonTemp2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_leftArrowButtonTemp2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_leftArrowButtonTemp2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_leftArrowButtonTemp2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_leftArrowButtonTemp2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_leftArrowButtonTemp2, &ui_img_leftarrowicon_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_pMScreenButtonVoc, ui_event_pMScreenButtonVoc, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_tempScreenButtonVoc, ui_event_tempScreenButtonVoc, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_co2ScreenButtonVoc, ui_event_co2ScreenButtonVoc, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_homeButtonVoc, ui_event_homeButtonVoc, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_settingsButtonVoc, ui_event_settingsButtonVoc, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_rightArrowButtonVoc, ui_event_rightArrowButtonVoc, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_leftArrowButtonTemp2, ui_event_leftArrowButtonTemp2, LV_EVENT_ALL, NULL);

}

void ui_vocScreen_screen_destroy(void)
{
    if(ui_vocScreen) lv_obj_del(ui_vocScreen);

    // NULL screen variables
    ui_vocScreen = NULL;
    ui_topPanelVoc = NULL;
    ui_pMScreenButtonVoc = NULL;
    ui_pMScreenButtonLabelVoc = NULL;
    ui_tempScreenButtonVoc = NULL;
    ui_tempScreenButtonLabelVoc = NULL;
    ui_vocScreenButtonVoc = NULL;
    ui_vocScreenButtonLabelVoc = NULL;
    ui_co2ScreenButtonVoc = NULL;
    ui_co2ScreenButtonLabelVoc = NULL;
    ui_vocScreenBackPanel = NULL;
    ui_vocPanel = NULL;
    ui_vocArc = NULL;
    ui_vocStateText = NULL;
    ui_vocValueText = NULL;
    ui_vocLabelText = NULL;
    ui_noxPanel = NULL;
    ui_noxArc = NULL;
    ui_noxStateText = NULL;
    ui_noxValueText = NULL;
    ui_noxLabelText = NULL;
    ui_homeButtonVoc = NULL;
    ui_settingsButtonVoc = NULL;
    ui_rightArrowButtonVoc = NULL;
    ui_leftArrowButtonTemp2 = NULL;

}
