// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: display_screens

#ifndef UI_CO2SCREEN_H
#define UI_CO2SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_co2Screen
extern void ui_co2Screen_screen_init(void);
extern void ui_co2Screen_screen_destroy(void);
extern lv_obj_t * ui_co2Screen;
extern lv_obj_t * ui_topPanelCO2;
extern void ui_event_pMScreenButtonCO2(lv_event_t * e);
extern lv_obj_t * ui_pMScreenButtonCO2;
extern lv_obj_t * ui_pMScreenButtonLabelCO2;
extern void ui_event_tempScreenButtonCO2(lv_event_t * e);
extern lv_obj_t * ui_tempScreenButtonCO2;
extern lv_obj_t * ui_tempScreenButtonLabelCO2;
extern void ui_event_vocScreenButtonVocCO2(lv_event_t * e);
extern lv_obj_t * ui_vocScreenButtonVocCO2;
extern lv_obj_t * ui_vocScreenButtonLabelCO2;
extern lv_obj_t * ui_co2ScreenButtonVocCO2;
extern lv_obj_t * ui_co2ScreenButtonLabelCO2;
extern lv_obj_t * ui_CO2ScreenBackPanel;
extern lv_obj_t * ui_CO2Panel;
extern lv_obj_t * ui_CO2Arc;
extern lv_obj_t * ui_CO2StateText;
extern lv_obj_t * ui_CO2ValueText;
extern lv_obj_t * ui_CO2LabelText;
extern void ui_event_homeButtonCO2(lv_event_t * e);
extern lv_obj_t * ui_homeButtonCO2;
extern void ui_event_settingsButtonCO2(lv_event_t * e);
extern lv_obj_t * ui_settingsButtonCO2;
extern void ui_event_leftArrowButtonCO2(lv_event_t * e);
extern lv_obj_t * ui_leftArrowButtonCO2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

