// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: display_screens

#ifndef UI_PMSCREEN_H
#define UI_PMSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_pmScreen
extern void ui_pmScreen_screen_init(void);
extern void ui_pmScreen_screen_destroy(void);
extern lv_obj_t * ui_pmScreen;
extern lv_obj_t * ui_topPanelPM;
extern lv_obj_t * ui_pMScreenButtonPM;
extern lv_obj_t * ui_pMScreenButtonLabel;
extern void ui_event_tempScreenButtonPM(lv_event_t * e);
extern lv_obj_t * ui_tempScreenButtonPM;
extern lv_obj_t * ui_tempScreenButtonLabel;
extern void ui_event_vocScreenButtonPM(lv_event_t * e);
extern lv_obj_t * ui_vocScreenButtonPM;
extern lv_obj_t * ui_vocScreenButtonLabel;
extern void ui_event_co2ScreenButtonPM(lv_event_t * e);
extern lv_obj_t * ui_co2ScreenButtonPM;
extern lv_obj_t * ui_co2ScreenButtonLabel;
extern lv_obj_t * ui_pmScreenBackPanel;
extern lv_obj_t * ui_pm10Panel;
extern lv_obj_t * ui_pm10Arc;
extern lv_obj_t * ui_pm10StateText;
extern lv_obj_t * ui_pm10ValueText;
extern lv_obj_t * ui_pm10LabelText;
extern lv_obj_t * ui_pm25Panel;
extern lv_obj_t * ui_pm25Arc;
extern lv_obj_t * ui_pm25StateText;
extern lv_obj_t * ui_pm25ValueText;
extern lv_obj_t * ui_pm25LabelText;
extern lv_obj_t * ui_pm40Panel;
extern lv_obj_t * ui_pm40Arc;
extern lv_obj_t * ui_pm40StateText;
extern lv_obj_t * ui_pm40ValueText;
extern lv_obj_t * ui_pm40LabelText;
extern lv_obj_t * ui_pm100Panel;
extern lv_obj_t * ui_pm100Arc;
extern lv_obj_t * ui_pm100StateText;
extern lv_obj_t * ui_pm100ValueText;
extern lv_obj_t * ui_pm100LabelText;
extern void ui_event_homeButtonPM(lv_event_t * e);
extern lv_obj_t * ui_homeButtonPM;
extern void ui_event_rightArrowButtonPM(lv_event_t * e);
extern lv_obj_t * ui_rightArrowButtonPM;
extern void ui_event_settingsButtonPM(lv_event_t * e);
extern lv_obj_t * ui_settingsButtonPM;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

