// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: display_screens

#ifndef UI_WIFISELECTIONSCREEN_H
#define UI_WIFISELECTIONSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_wifiSelectionScreen
extern void ui_wifiSelectionScreen_screen_init(void);
extern void ui_wifiSelectionScreen_screen_destroy(void);
extern lv_obj_t * ui_wifiSelectionScreen;
extern void ui_event_topPanelWiFiSelectionScreen(lv_event_t * e);
extern lv_obj_t * ui_topPanelWiFiSelectionScreen;
extern lv_obj_t * ui_wiFiSelectionScreenButtonWiFi;
extern lv_obj_t * ui_wiFiScreenButtonLabelWiFi;
extern void ui_event_sdScreenButtonWiFi(lv_event_t * e);
extern lv_obj_t * ui_sdScreenButtonWiFi;
extern lv_obj_t * ui_sdScreenButtonLabelWiFi;
extern lv_obj_t * ui_WiFiSelectionScreenBackPanel;
extern void ui_event_WiFiSelectionScreenDropdown(lv_event_t * e);
extern lv_obj_t * ui_WiFiSelectionScreenDropdown;
extern void ui_event_WiFiSelectionScreenPwdInputTextArea(lv_event_t * e);
extern lv_obj_t * ui_WiFiSelectionScreenPwdInputTextArea;
extern lv_obj_t * ui_ConnectedWiFiPanelWiFiSelectionScreen;
extern lv_obj_t * ui_ConnectedWiFiNameLabelWiFiSelectionScreen;
extern lv_obj_t * ui_ConnectedWiFiStatusLabelWiFiSelectionScreen1;
extern void ui_event_ForgetWiFiButtonWiFiSelectionScreen(lv_event_t * e);
extern lv_obj_t * ui_ForgetWiFiButtonWiFiSelectionScreen;
extern lv_obj_t * ui_ForgetWiFiButtonLabelWiFiSelectionScreen;
extern void ui_event_homeButtonWiFi(lv_event_t * e);
extern lv_obj_t * ui_homeButtonWiFi;
extern void ui_event_KeyboardWiFiSelectionScreen(lv_event_t * e);
extern lv_obj_t * ui_KeyboardWiFiSelectionScreen;
extern lv_obj_t * ui_LoadingPanelWiFiSelectionScreen;
extern lv_obj_t * ui_spinnerWiFiSelectionScreen;
extern lv_obj_t * ui_FailedConnectionPanelWiFiSelectionScreen;
extern lv_obj_t * ui_FailedConnectionLabelWiFiSelectionScreen;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

