// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: display_screens

#ifndef _DISPLAY_SCREENS_UI_H
#define _DISPLAY_SCREENS_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "ui_airQualityScreen.h"
#include "ui_pmScreen.h"
#include "ui_tempScreen.h"
#include "ui_vocScreen.h"
#include "ui_co2Screen.h"
#include "ui_wifiSelectionScreen.h"
#include "ui_sdScreen.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * FadeToStart_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * showSideBar_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_settingsicon_png);    // assets/settingsIcon.png
LV_IMG_DECLARE(ui_img_homeicon_png);    // assets/homeIcon.png
LV_IMG_DECLARE(ui_img_rightarrowicon_png);    // assets/rightArrowIcon.png
LV_IMG_DECLARE(ui_img_leftarrowicon_png);    // assets/leftArrowIcon.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
