// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: display_screens

#ifndef UI_AIRQUALITYSCREEN_H
#define UI_AIRQUALITYSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_airQualityScreen
extern void ui_airQualityScreen_screen_init(void);
extern void ui_airQualityScreen_screen_destroy(void);
extern lv_obj_t * ui_airQualityScreen;
extern lv_obj_t * ui_airQualityScreenBackPanel;
extern lv_obj_t * ui_airQualityArc;
extern lv_obj_t * ui_airQualityStateText;
extern lv_obj_t * ui_airQualityLabelText;
extern void ui_event_SeeStatButton(lv_event_t * e);
extern lv_obj_t * ui_SeeStatButton;
extern lv_obj_t * ui_SeeStatButtonLabel;
extern void ui_event_settingsButtonMain(lv_event_t * e);
extern lv_obj_t * ui_settingsButtonMain;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

