// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: display_screens

#include "ui.h"

lv_obj_t * ui_tempScreen = NULL;
lv_obj_t * ui_topPanelTemp = NULL;
lv_obj_t * ui_pMScreenButtonTemp = NULL;
lv_obj_t * ui_pMScreenButtonLabel1 = NULL;
lv_obj_t * ui_tempScreenButtonTemp = NULL;
lv_obj_t * ui_tempScreenButtonLabel1 = NULL;
lv_obj_t * ui_vocScreenButtonTemp = NULL;
lv_obj_t * ui_vocScreenButtonLabel1 = NULL;
lv_obj_t * ui_co2ScreenButtonTemp = NULL;
lv_obj_t * ui_co2ScreenButtonLabel1 = NULL;
lv_obj_t * ui_tempScreenBackPanel = NULL;
lv_obj_t * ui_tempPanel = NULL;
lv_obj_t * ui_tempArc = NULL;
lv_obj_t * ui_tempStateText = NULL;
lv_obj_t * ui_tempValueText = NULL;
lv_obj_t * ui_tempLabelText = NULL;
lv_obj_t * ui_humPanel = NULL;
lv_obj_t * ui_humArc = NULL;
lv_obj_t * ui_humStateText = NULL;
lv_obj_t * ui_humValueText = NULL;
lv_obj_t * ui_humLabelText = NULL;
lv_obj_t * ui_homeButtonTemp = NULL;
lv_obj_t * ui_settingsButtonTemp = NULL;
lv_obj_t * ui_rightArrowButtonTemp = NULL;
lv_obj_t * ui_leftArrowButtonTemp = NULL;
// event funtions
void ui_event_pMScreenButtonTemp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_pmScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_pmScreen_screen_init);
        _ui_screen_delete(&ui_tempScreen);
    }
}

void ui_event_vocScreenButtonTemp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_vocScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_vocScreen_screen_init);
        _ui_screen_delete(&ui_tempScreen);
    }
}

void ui_event_co2ScreenButtonTemp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_co2Screen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_co2Screen_screen_init);
        _ui_screen_delete(&ui_tempScreen);
    }
}

void ui_event_homeButtonTemp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_airQualityScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_airQualityScreen_screen_init);
        _ui_screen_delete(&ui_tempScreen);
    }
}

void ui_event_settingsButtonTemp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_wifiSelectionScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_wifiSelectionScreen_screen_init);
        _ui_screen_delete(&ui_tempScreen);
    }
}

void ui_event_rightArrowButtonTemp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_vocScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_vocScreen_screen_init);
        _ui_screen_delete(&ui_tempScreen);
    }
}

void ui_event_leftArrowButtonTemp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_pmScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_pmScreen_screen_init);
        _ui_screen_delete(&ui_tempScreen);
    }
}

// build funtions

void ui_tempScreen_screen_init(void)
{
    ui_tempScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_tempScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_topPanelTemp = lv_obj_create(ui_tempScreen);
    lv_obj_set_width(ui_topPanelTemp, 327);
    lv_obj_set_height(ui_topPanelTemp, 30);
    lv_obj_set_x(ui_topPanelTemp, 0);
    lv_obj_set_y(ui_topPanelTemp, -100);
    lv_obj_set_align(ui_topPanelTemp, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_topPanelTemp, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_topPanelTemp, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_topPanelTemp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_topPanelTemp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_topPanelTemp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_topPanelTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_topPanelTemp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pMScreenButtonTemp = lv_button_create(ui_topPanelTemp);
    lv_obj_set_width(ui_pMScreenButtonTemp, 58);
    lv_obj_set_height(ui_pMScreenButtonTemp, 30);
    lv_obj_set_x(ui_pMScreenButtonTemp, 0);
    lv_obj_set_y(ui_pMScreenButtonTemp, -37);
    lv_obj_set_align(ui_pMScreenButtonTemp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pMScreenButtonTemp, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_pMScreenButtonTemp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pMScreenButtonTemp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pMScreenButtonTemp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pMScreenButtonTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pMScreenButtonLabel1 = lv_label_create(ui_pMScreenButtonTemp);
    lv_obj_set_width(ui_pMScreenButtonLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pMScreenButtonLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_pMScreenButtonLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pMScreenButtonLabel1, "PM");
    lv_obj_set_style_text_font(ui_pMScreenButtonLabel1, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempScreenButtonTemp = lv_button_create(ui_topPanelTemp);
    lv_obj_set_width(ui_tempScreenButtonTemp, 58);
    lv_obj_set_height(ui_tempScreenButtonTemp, 30);
    lv_obj_set_x(ui_tempScreenButtonTemp, 0);
    lv_obj_set_y(ui_tempScreenButtonTemp, -37);
    lv_obj_set_align(ui_tempScreenButtonTemp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_tempScreenButtonTemp, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_tempScreenButtonTemp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_tempScreenButtonTemp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_tempScreenButtonTemp, lv_color_hex(0x7C9EE7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_tempScreenButtonTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempScreenButtonLabel1 = lv_label_create(ui_tempScreenButtonTemp);
    lv_obj_set_width(ui_tempScreenButtonLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tempScreenButtonLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_tempScreenButtonLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tempScreenButtonLabel1, "TEMP");
    lv_obj_set_style_text_font(ui_tempScreenButtonLabel1, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_vocScreenButtonTemp = lv_button_create(ui_topPanelTemp);
    lv_obj_set_width(ui_vocScreenButtonTemp, 58);
    lv_obj_set_height(ui_vocScreenButtonTemp, 30);
    lv_obj_set_x(ui_vocScreenButtonTemp, 0);
    lv_obj_set_y(ui_vocScreenButtonTemp, -37);
    lv_obj_set_align(ui_vocScreenButtonTemp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_vocScreenButtonTemp, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_vocScreenButtonTemp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_vocScreenButtonTemp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_vocScreenButtonTemp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_vocScreenButtonTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_vocScreenButtonLabel1 = lv_label_create(ui_vocScreenButtonTemp);
    lv_obj_set_width(ui_vocScreenButtonLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_vocScreenButtonLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_vocScreenButtonLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_vocScreenButtonLabel1, "VOC");
    lv_obj_set_style_text_font(ui_vocScreenButtonLabel1, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_co2ScreenButtonTemp = lv_button_create(ui_topPanelTemp);
    lv_obj_set_width(ui_co2ScreenButtonTemp, 58);
    lv_obj_set_height(ui_co2ScreenButtonTemp, 30);
    lv_obj_set_x(ui_co2ScreenButtonTemp, 0);
    lv_obj_set_y(ui_co2ScreenButtonTemp, -37);
    lv_obj_set_align(ui_co2ScreenButtonTemp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_co2ScreenButtonTemp, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_co2ScreenButtonTemp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_co2ScreenButtonTemp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_co2ScreenButtonTemp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_co2ScreenButtonTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_co2ScreenButtonLabel1 = lv_label_create(ui_co2ScreenButtonTemp);
    lv_obj_set_width(ui_co2ScreenButtonLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_co2ScreenButtonLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_co2ScreenButtonLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_co2ScreenButtonLabel1, "CO2");
    lv_obj_set_style_text_font(ui_co2ScreenButtonLabel1, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempScreenBackPanel = lv_obj_create(ui_tempScreen);
    lv_obj_set_width(ui_tempScreenBackPanel, 267);
    lv_obj_set_height(ui_tempScreenBackPanel, 194);
    lv_obj_set_x(ui_tempScreenBackPanel, 0);
    lv_obj_set_y(ui_tempScreenBackPanel, 19);
    lv_obj_set_align(ui_tempScreenBackPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_tempScreenBackPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_tempScreenBackPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_tempScreenBackPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_tempScreenBackPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_tempScreenBackPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempPanel = lv_obj_create(ui_tempScreenBackPanel);
    lv_obj_set_width(ui_tempPanel, 82);
    lv_obj_set_height(ui_tempPanel, 85);
    lv_obj_set_x(ui_tempPanel, -64);
    lv_obj_set_y(ui_tempPanel, -15);
    lv_obj_set_align(ui_tempPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_tempPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_tempPanel, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_tempPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempArc = lv_arc_create(ui_tempPanel);
    lv_obj_set_width(ui_tempArc, 63);
    lv_obj_set_height(ui_tempArc, 64);
    lv_obj_set_align(ui_tempArc, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_tempArc, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK |
                       LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags
    lv_arc_set_range(ui_tempArc, 18, 26);
    lv_arc_set_value(ui_tempArc, 21);
    lv_obj_set_style_arc_color(ui_tempArc, lv_color_hex(0x707F78), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_tempArc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_tempArc, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_tempArc, lv_color_hex(0x0DB863), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_tempArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_tempArc, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_tempArc, lv_color_hex(0x84D4AC), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_tempArc, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_tempArc, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_tempArc, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_tempArc, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_tempArc, 2, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_tempStateText = lv_label_create(ui_tempPanel);
    lv_obj_set_width(ui_tempStateText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tempStateText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_tempStateText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tempStateText, "GOOD");
    lv_obj_set_style_text_color(ui_tempStateText, lv_color_hex(0x0DB863), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tempStateText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_tempStateText, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tempStateText, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempValueText = lv_label_create(ui_tempPanel);
    lv_obj_set_width(ui_tempValueText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tempValueText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tempValueText, 1);
    lv_obj_set_y(ui_tempValueText, 19);
    lv_obj_set_align(ui_tempValueText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tempValueText, "20");
    lv_obj_set_style_text_color(ui_tempValueText, lv_color_hex(0x0DB863), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tempValueText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_tempValueText, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tempValueText, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempLabelText = lv_label_create(ui_tempPanel);
    lv_obj_set_width(ui_tempLabelText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tempLabelText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tempLabelText, 1);
    lv_obj_set_y(ui_tempLabelText, 32);
    lv_obj_set_align(ui_tempLabelText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tempLabelText, "Temp");
    lv_obj_set_style_text_color(ui_tempLabelText, lv_color_hex(0x0DB863), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tempLabelText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_tempLabelText, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tempLabelText, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_humPanel = lv_obj_create(ui_tempScreenBackPanel);
    lv_obj_set_width(ui_humPanel, 82);
    lv_obj_set_height(ui_humPanel, 85);
    lv_obj_set_x(ui_humPanel, 64);
    lv_obj_set_y(ui_humPanel, -15);
    lv_obj_set_align(ui_humPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_humPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_humPanel, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_humPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_humArc = lv_arc_create(ui_humPanel);
    lv_obj_set_width(ui_humArc, 63);
    lv_obj_set_height(ui_humArc, 64);
    lv_obj_set_align(ui_humArc, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_humArc, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK |
                       LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags
    lv_arc_set_range(ui_humArc, 20, 70);
    lv_arc_set_value(ui_humArc, 60);
    lv_obj_set_style_arc_color(ui_humArc, lv_color_hex(0x707F78), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_humArc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_humArc, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_humArc, lv_color_hex(0xDF1919), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_humArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_humArc, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_humArc, lv_color_hex(0xD48484), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_humArc, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_humArc, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_humArc, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_humArc, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_humArc, 2, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_humStateText = lv_label_create(ui_humPanel);
    lv_obj_set_width(ui_humStateText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_humStateText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_humStateText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_humStateText, "HUMID");
    lv_obj_set_style_text_color(ui_humStateText, lv_color_hex(0xDF1919), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_humStateText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_humStateText, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_humStateText, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_humValueText = lv_label_create(ui_humPanel);
    lv_obj_set_width(ui_humValueText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_humValueText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_humValueText, 1);
    lv_obj_set_y(ui_humValueText, 19);
    lv_obj_set_align(ui_humValueText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_humValueText, "60");
    lv_obj_set_style_text_color(ui_humValueText, lv_color_hex(0xDF1919), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_humValueText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_humValueText, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_humValueText, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_humLabelText = lv_label_create(ui_humPanel);
    lv_obj_set_width(ui_humLabelText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_humLabelText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_humLabelText, 1);
    lv_obj_set_y(ui_humLabelText, 32);
    lv_obj_set_align(ui_humLabelText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_humLabelText, "Hum");
    lv_obj_set_style_text_color(ui_humLabelText, lv_color_hex(0xDF1919), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_humLabelText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_humLabelText, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_humLabelText, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_homeButtonTemp = lv_button_create(ui_tempScreenBackPanel);
    lv_obj_set_width(ui_homeButtonTemp, 30);
    lv_obj_set_height(ui_homeButtonTemp, 30);
    lv_obj_set_x(ui_homeButtonTemp, 0);
    lv_obj_set_y(ui_homeButtonTemp, 77);
    lv_obj_set_align(ui_homeButtonTemp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_homeButtonTemp, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_homeButtonTemp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_homeButtonTemp, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_homeButtonTemp, lv_color_hex(0x7C9EE7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_homeButtonTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_homeButtonTemp, &ui_img_homeicon_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settingsButtonTemp = lv_button_create(ui_tempScreen);
    lv_obj_set_width(ui_settingsButtonTemp, 34);
    lv_obj_set_height(ui_settingsButtonTemp, 30);
    lv_obj_set_x(ui_settingsButtonTemp, 140);
    lv_obj_set_y(ui_settingsButtonTemp, -101);
    lv_obj_set_align(ui_settingsButtonTemp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_settingsButtonTemp, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_settingsButtonTemp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_settingsButtonTemp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_settingsButtonTemp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_settingsButtonTemp, &ui_img_settingsicon_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rightArrowButtonTemp = lv_button_create(ui_tempScreen);
    lv_obj_set_width(ui_rightArrowButtonTemp, 25);
    lv_obj_set_height(ui_rightArrowButtonTemp, 67);
    lv_obj_set_x(ui_rightArrowButtonTemp, 144);
    lv_obj_set_y(ui_rightArrowButtonTemp, 0);
    lv_obj_set_align(ui_rightArrowButtonTemp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_rightArrowButtonTemp, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_rightArrowButtonTemp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_rightArrowButtonTemp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rightArrowButtonTemp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_rightArrowButtonTemp, &ui_img_rightarrowicon_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_leftArrowButtonTemp = lv_button_create(ui_tempScreen);
    lv_obj_set_width(ui_leftArrowButtonTemp, 28);
    lv_obj_set_height(ui_leftArrowButtonTemp, 67);
    lv_obj_set_x(ui_leftArrowButtonTemp, -138);
    lv_obj_set_y(ui_leftArrowButtonTemp, 0);
    lv_obj_set_align(ui_leftArrowButtonTemp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_leftArrowButtonTemp, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_leftArrowButtonTemp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_leftArrowButtonTemp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_leftArrowButtonTemp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_leftArrowButtonTemp, &ui_img_leftarrowicon_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_pMScreenButtonTemp, ui_event_pMScreenButtonTemp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_vocScreenButtonTemp, ui_event_vocScreenButtonTemp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_co2ScreenButtonTemp, ui_event_co2ScreenButtonTemp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_homeButtonTemp, ui_event_homeButtonTemp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_settingsButtonTemp, ui_event_settingsButtonTemp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_rightArrowButtonTemp, ui_event_rightArrowButtonTemp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_leftArrowButtonTemp, ui_event_leftArrowButtonTemp, LV_EVENT_ALL, NULL);

}

void ui_tempScreen_screen_destroy(void)
{
    if(ui_tempScreen) lv_obj_del(ui_tempScreen);

    // NULL screen variables
    ui_tempScreen = NULL;
    ui_topPanelTemp = NULL;
    ui_pMScreenButtonTemp = NULL;
    ui_pMScreenButtonLabel1 = NULL;
    ui_tempScreenButtonTemp = NULL;
    ui_tempScreenButtonLabel1 = NULL;
    ui_vocScreenButtonTemp = NULL;
    ui_vocScreenButtonLabel1 = NULL;
    ui_co2ScreenButtonTemp = NULL;
    ui_co2ScreenButtonLabel1 = NULL;
    ui_tempScreenBackPanel = NULL;
    ui_tempPanel = NULL;
    ui_tempArc = NULL;
    ui_tempStateText = NULL;
    ui_tempValueText = NULL;
    ui_tempLabelText = NULL;
    ui_humPanel = NULL;
    ui_humArc = NULL;
    ui_humStateText = NULL;
    ui_humValueText = NULL;
    ui_humLabelText = NULL;
    ui_homeButtonTemp = NULL;
    ui_settingsButtonTemp = NULL;
    ui_rightArrowButtonTemp = NULL;
    ui_leftArrowButtonTemp = NULL;

}
