// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: display_screens

#ifndef UI_TEMPSCREEN_H
#define UI_TEMPSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_tempScreen
extern void ui_tempScreen_screen_init(void);
extern void ui_tempScreen_screen_destroy(void);
extern lv_obj_t * ui_tempScreen;
extern lv_obj_t * ui_topPanelTemp;
extern void ui_event_pMScreenButtonTemp(lv_event_t * e);
extern lv_obj_t * ui_pMScreenButtonTemp;
extern lv_obj_t * ui_pMScreenButtonLabel1;
extern lv_obj_t * ui_tempScreenButtonTemp;
extern lv_obj_t * ui_tempScreenButtonLabel1;
extern void ui_event_vocScreenButtonTemp(lv_event_t * e);
extern lv_obj_t * ui_vocScreenButtonTemp;
extern lv_obj_t * ui_vocScreenButtonLabel1;
extern void ui_event_co2ScreenButtonTemp(lv_event_t * e);
extern lv_obj_t * ui_co2ScreenButtonTemp;
extern lv_obj_t * ui_co2ScreenButtonLabel1;
extern lv_obj_t * ui_tempScreenBackPanel;
extern lv_obj_t * ui_tempPanel;
extern lv_obj_t * ui_tempArc;
extern lv_obj_t * ui_tempStateText;
extern lv_obj_t * ui_tempValueText;
extern lv_obj_t * ui_tempLabelText;
extern lv_obj_t * ui_humPanel;
extern lv_obj_t * ui_humArc;
extern lv_obj_t * ui_humStateText;
extern lv_obj_t * ui_humValueText;
extern lv_obj_t * ui_humLabelText;
extern void ui_event_homeButtonTemp(lv_event_t * e);
extern lv_obj_t * ui_homeButtonTemp;
extern void ui_event_settingsButtonTemp(lv_event_t * e);
extern lv_obj_t * ui_settingsButtonTemp;
extern void ui_event_rightArrowButtonTemp(lv_event_t * e);
extern lv_obj_t * ui_rightArrowButtonTemp;
extern void ui_event_leftArrowButtonTemp(lv_event_t * e);
extern lv_obj_t * ui_leftArrowButtonTemp;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

