// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: display_screens

#ifndef UI_VOCSCREEN_H
#define UI_VOCSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_vocScreen
extern void ui_vocScreen_screen_init(void);
extern void ui_vocScreen_screen_destroy(void);
extern lv_obj_t * ui_vocScreen;
extern lv_obj_t * ui_topPanelVoc;
extern void ui_event_pMScreenButtonVoc(lv_event_t * e);
extern lv_obj_t * ui_pMScreenButtonVoc;
extern lv_obj_t * ui_pMScreenButtonLabelVoc;
extern void ui_event_tempScreenButtonVoc(lv_event_t * e);
extern lv_obj_t * ui_tempScreenButtonVoc;
extern lv_obj_t * ui_tempScreenButtonLabelVoc;
extern lv_obj_t * ui_vocScreenButtonVoc;
extern lv_obj_t * ui_vocScreenButtonLabelVoc;
extern void ui_event_co2ScreenButtonVoc(lv_event_t * e);
extern lv_obj_t * ui_co2ScreenButtonVoc;
extern lv_obj_t * ui_co2ScreenButtonLabelVoc;
extern lv_obj_t * ui_vocScreenBackPanel;
extern lv_obj_t * ui_vocPanel;
extern lv_obj_t * ui_vocArc;
extern lv_obj_t * ui_vocStateText;
extern lv_obj_t * ui_vocValueText;
extern lv_obj_t * ui_vocLabelText;
extern lv_obj_t * ui_noxPanel;
extern lv_obj_t * ui_noxArc;
extern lv_obj_t * ui_noxStateText;
extern lv_obj_t * ui_noxValueText;
extern lv_obj_t * ui_noxLabelText;
extern void ui_event_homeButtonVoc(lv_event_t * e);
extern lv_obj_t * ui_homeButtonVoc;
extern void ui_event_settingsButtonVoc(lv_event_t * e);
extern lv_obj_t * ui_settingsButtonVoc;
extern void ui_event_rightArrowButtonVoc(lv_event_t * e);
extern lv_obj_t * ui_rightArrowButtonVoc;
extern void ui_event_leftArrowButtonTemp2(lv_event_t * e);
extern lv_obj_t * ui_leftArrowButtonTemp2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

